"""Phase 14 — in-season weekly digest: rank-snapshot + diff + projection engine.

This is the *data core* of the digest email — pure logic, no network / SMTP, so
it is fully unit-testable offline against the built CSVs. `scripts/build_digest.py`
wires it to `exports/`; `scripts/send_digest.py` mails the rendered HTML.

The digest is deliberately **over-inclusive**: instead of a hand-curated set of
"headline" stats, it auto-discovers *every* numeric column in the ranked sheets
and reports movement on all of them. Two kinds of item:

  1. **All-time crossings** (players + teams). For every numeric column in
     `player_all_time` / `team_all_time`, watch the top and bottom `WINDOW` of
     the leaderboard and report when an entity crosses another there
     (e.g. "Kyler Murray passes JJ McCarthy for 4th-lowest Points all-time").
     Detected by diffing this week's ranking snapshot against last week's.

  2. **Yearly on-pace projections** (players + teams + league). For every
     numeric column in `player_year` / `team_year` / `league_year`, project the
     in-progress season to a full-season pace (cumulative stats scale by weeks
     played; rate/level stats carry as-is) and report where the projection lands
     in the top/bottom `WINDOW` versus every completed season
     (e.g. "Oliverwkw is on pace for 4th-highest Hardship this season").
     **Yearly items are withheld until week 3** (too little signal earlier), per
     the phase spec.

`plan/phase14_phrasing.csv` (generated by `phrasing_catalog()`) documents the
exact sentence template for every discovered stat.
"""
from __future__ import annotations

from collections import Counter as _Counter
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple
import json
import math

import pandas as pd

from .email_summary import stat_relevance



# ---------------------------------------------------------------------------
# Tunables
# ---------------------------------------------------------------------------
# Default top/bottom N of a leaderboard that counts as a notable "move".
WINDOW = 5

# Yearly ("on pace") items are withheld until this many weeks are complete.
MIN_YEARLY_WEEK = 3

# Per-section rules for ALL-TIME crossings (diff of this week's ranking vs last):
#   * players: huge board -> watch the top AND bottom 5, cap at half the board.
#   * teams: only 8 of them, so report ANY movement among the 8. High end only
#     (every rank change has a riser; reporting the riser once avoids the
#     double "riser Nth-highest + faller Mth-lowest" for a single swap), full
#     board (window=None), no half cap.
# league_all_time is a single row (no ranking) -> handled by milestones instead.
CROSSING_CONFIG = {
    "players": {"ends": ("high", "low"), "window": WINDOW, "cap_half": True},
    "teams":   {"ends": ("high",),       "window": None,   "cap_half": False},
}

# Per-section window for YEARLY on-pace projections. players/teams fixed at 5;
# league_year uses floor(#seasons / 3) capped at 5 (few seasons -> tiny window).
PROJECTION_WINDOW = {"players": WINDOW, "teams": WINDOW}
LEAGUE_WINDOW_CAP = 5

# league_all_time "major" cumulative totals that earn a milestone note when they
# cross a round number. (No leaderboard for a single-row sheet.)
MAJOR_LEAGUE_STATS = (
    "PF", "Number of Add/Drops", "Total transactions", "Total trades", "Amount of FAAB spent",
)

# Sentinels the build writes for "no value" — treated as missing for ranking.
_MISSING = {"N/A", "In Progress", "", "None", "nan", "NaN"}

# Columns that are identity / keys, never ranked even though some are numeric.
_KEY_COLS = {
    "Player", "Team", "Year", "Week", "Week Name", "Opponent",
    "Top team", "Top Team", "Last team", "Rookie?", "Result",
    "Taxi-eligible",
}

# A yearly stat is treated as a *rate/level* (projected as-is, not scaled by
# weeks played) when its name contains any of these markers; otherwise it is a
# *cumulative* count/total and scales linearly with weeks played. This split is
# surfaced in the phrasing CSV so it can be reviewed and corrected per column.
_RATE_MARKERS = (
    "%", "avg", "average", "ppg", "per game", "per season", "win %",
    "efficiency", "skill", "percentile", "volatility", "floor", "ceiling",
    "age", "variance", "differential", "boom", "bust", "quartile",
    "middle 50", "range", "diff", "streak", "remaining", "rate",
    "highest starter", "lowest starter", "playoff tiebreaker",
    # "Most number of {players,QBs,RBs,WRs,TE} {rostered,started} from same NFL
    # team" is a season MAX, not a running total — it's capped by roster size, so
    # scaling it by weeks-remaining produces impossible values that always rank
    # 1st (6 -> 12.8 at week 8, vs an all-time high of 7). See F2 in
    # plan/AUDIT_PHASE14_3PART.md.
    "most number of",
)


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------
def _to_float(value) -> Optional[float]:
    """Parse a cell to float, or None for sentinels / unparseable values."""
    if value is None:
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    s = str(value).strip()
    if s in _MISSING:
        return None
    s = s.replace(",", "").rstrip("%")
    try:
        return float(s)
    except ValueError:
        return None


def _place(rank: int, end: str) -> str:
    """"highest" / "lowest" for 1st, "2nd-highest" and so on below it.

    "1st-highest" says the same thing twice — "highest" already means first — and
    the doubling is loudest on exactly the lines that matter most. Ranks below
    first still need the ordinal to mean anything."""
    end_word = "highest" if end == "high" else "lowest"
    return end_word if rank == 1 else f"{_ordinal(rank)}-{end_word}"


def _ordinal(n: int) -> str:
    if 10 <= (n % 100) <= 20:
        suf = "th"
    else:
        suf = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suf}"


def _fmt(value: float) -> str:
    """Compact number render: ints as grouped ints, else 1 decimal."""
    if abs(value - round(value)) < 1e-9:
        return f"{int(round(value)):,}"
    return f"{value:,.1f}"


def is_rate_stat(column: str) -> bool:
    """True if a yearly stat is a rate/level (projected as-is, not scaled)."""
    c = column.lower()
    return any(m in c for m in _RATE_MARKERS)


def is_weekly_counting_stat(column: str) -> bool:
    """True for stats that tally a per-week boolean outcome (max one per week) —
    the weekly awards (`Times ...`) and the result-flip counterfactuals
    (`Wins/Losses from hardship`, `Wins/Losses from byes`). These do NOT get an
    on-pace projection (you can't be "on pace for 8.5 awards"); movement on them
    is surfaced only through their all-time crossings (players top/bottom 5,
    teams any-of-8)."""
    c = column.lower()
    return c.startswith("times ") or "wins from" in c or "losses from" in c


# ---------------------------------------------------------------------------
# Column discovery
# ---------------------------------------------------------------------------
def discover_numeric_columns(df: pd.DataFrame, entity_col: str,
                             extra_skip: Sequence[str] = ()) -> List[str]:
    """Every column that ranks: not a key, and with >= 2 numeric values.

    Record strings ("34-20"), result labels ("Champion"), and team-name columns
    fail float parsing and are dropped automatically, so this stays truly
    over-inclusive without a hand-maintained exclusion list.
    """
    skip = set(_KEY_COLS) | {entity_col} | set(extra_skip)
    cols: List[str] = []
    for c in df.columns:
        if c in skip:
            continue
        numeric = sum(1 for v in df[c] if _to_float(v) is not None)
        if numeric >= 2:
            cols.append(c)
    return cols


# ---------------------------------------------------------------------------
# Mirrored (zero-centred) columns
# ---------------------------------------------------------------------------
# Some columns hold the SAME fact twice with opposite signs: a matchup's margin
# is +M for the winner and -M for the loser, a trade's net KTC is +X for one side
# and -X for the other. Ranking the raw values would report one fact as two
# records — the biggest blowout AND the biggest defeat, always the same game — and
# would fill the bottom of every such board with the mirror images of its top.
# So a mirrored column is ranked over its POSITIVE values only: "highest
# Margin" is the biggest blowout, "lowest Margin" the closest game, each named
# once, from the side that came out ahead.
#
# Detected STRUCTURALLY (two_sided_columns), from rows that pair up through a
# counterpart column — not from the shape of the distribution. A distribution
# test would also catch `Change from previous week`, which is symmetric because
# players gain and lose about equally often, and clipping it to positives would
# throw away "biggest drop from last week" — a real record, not a mirror image.
# sheet -> (the row's side, the column naming the other side, the columns that
# identify the shared event). Only sheets whose rows come in sides can mirror.
_MIRROR_PAIRS = {
    "team_week": ("Team", "Opponent", ("Year", "Week")),
    "trades": ("Team", "Team's traded with 1", ("Date", "Season")),
}


def mirrored_columns(df: pd.DataFrame, sheet: str) -> set:
    """The columns of `sheet` that hold one fact from both sides."""
    pair = _MIRROR_PAIRS.get(sheet)
    if not pair or df is None or df.empty or pair[1] not in df.columns:
        return set()
    return set(two_sided_columns(df, pair[0], pair[1], list(pair[2])))


def numeric_series(df: pd.DataFrame, column: str) -> "pd.Series":
    """The column as floats, sentinels ("N/A", "In Progress") dropped. Uses the
    vectorised parser when the column is already numeric — the weekly sheets are
    20k rows deep and a per-cell Python parse over every column is the difference
    between a build step and a coffee break."""
    col = df[column]
    if pd.api.types.is_numeric_dtype(col):
        return pd.to_numeric(col, errors="coerce").dropna()
    return pd.to_numeric(col.map(_to_float), errors="coerce").dropna()


def rankable_series(df: pd.DataFrame, column: str, mirrored: bool = False) -> "pd.Series":
    """`numeric_series`, reduced to the positive side when the column mirrors."""
    s = numeric_series(df, column)
    return s[s > 0] if mirrored else s


# ---------------------------------------------------------------------------
# Rankings (descending: index 0 = highest value; tail = lowest)
# ---------------------------------------------------------------------------
def rank_column(df: pd.DataFrame, entity_col: str, column: str) -> List[dict]:
    """Ordered [{'entity','value'}] high -> low for one column (ties by name)."""
    if column not in df.columns or entity_col not in df.columns:
        return []
    rows = []
    for _, r in df.iterrows():
        v = _to_float(r[column])
        if v is None:
            continue
        rows.append({"entity": str(r[entity_col]), "value": v})
    rows.sort(key=lambda e: (-e["value"], e["entity"]))
    return rows


def competition_ranks(values: Sequence[float], end: str) -> Dict[float, int]:
    """value -> competition ("1224") rank from the watched `end`.

    Tied values share the smallest rank they'd occupy, and the next distinct
    value's rank skips by the count of tied values above it — a two-way tie for
    1st makes the next value 3rd, not 2nd. This is what lets tied rows take up
    the requisite number of the top-N slots."""
    counts = _Counter(values)
    ordered = sorted(counts, reverse=(end == "high"))
    ranks: Dict[float, int] = {}
    pos = 1
    for v in ordered:
        ranks[v] = pos
        pos += counts[v]
    return ranks


def _name_list(names: Sequence[str]) -> str:
    """"X" / "X and Y" / "X, Y and Z" — the way a person would read a short list."""
    names = list(names)
    if not names:
        return ""
    if len(names) == 1:
        return names[0]
    if len(names) == 2:
        return f"{names[0]} and {names[1]}"
    return f"{', '.join(names[:-1])} and {names[-1]}"


# The largest tie a "joins a tie" line will report. Joining a tie bigger than
# this (6+ holders including the mover) is not worth a line — the value is too
# common to be news — so it is suppressed entirely (Change 4).
_MAX_JOIN_TIE = 5


def _crossing_detail(joined: bool, others: Sequence[str], passed: Sequence[str],
                     place: str, column: str, value: Optional[float]) -> str:
    """Shared phrasing for an all-time / event-board move.

    joined:  the mover ARRIVED at a value others already hold (a tie), rather
             than displacing anyone. Two-way -> name the one other holder;
             three-to-five-way -> just "joins a tie for".
    passed:  the entities the mover overtook (one, or several when it leapt a
             whole tie), named in full."""
    val = f" ({_fmt(value)})" if value is not None else ""
    if joined:
        if len(others) == 1:
            return f"joins a tie with {others[0]} for {place} {column}{val}"
        return f"joins a tie for {place} {column}{val}"
    return f"passes {_name_list(passed)} for {place} {column}{val}"


def _rankings_for(df: pd.DataFrame, entity_col: str,
                  columns: Sequence[str]) -> Dict[str, List[dict]]:
    out: Dict[str, List[dict]] = {}
    for col in columns:
        ranked = rank_column(df, entity_col, col)
        if len(ranked) >= 2:
            out[col] = ranked
    return out


# ---------------------------------------------------------------------------
# Season / week helpers
# ---------------------------------------------------------------------------
def current_season(team_year: pd.DataFrame) -> Optional[int]:
    if "Year" not in team_year.columns:
        return None
    yrs = pd.to_numeric(team_year["Year"], errors="coerce").dropna()
    return int(yrs.max()) if len(yrs) else None


def weeks_completed(team_week: pd.DataFrame, season: int) -> int:
    """Distinct completed weeks for `season` (the build only writes a week once
    it is final, per the Phase 5E freshness gate). 0 => offseason."""
    if team_week.empty or "Year" not in team_week.columns or "Week" not in team_week.columns:
        return 0
    sub = team_week[pd.to_numeric(team_week["Year"], errors="coerce") == season]
    weeks = pd.to_numeric(sub["Week"], errors="coerce").dropna().unique()
    return int(len(weeks))


# ---------------------------------------------------------------------------
# Snapshot (all-time rankings, for week-over-week diffing)
# ---------------------------------------------------------------------------
def build_snapshot(
    player_all_time: pd.DataFrame,
    team_all_time: pd.DataFrame,
    team_year: pd.DataFrame,
    team_week: pd.DataFrame,
    league_all_time: Optional[pd.DataFrame] = None,
    captured_at: Optional[datetime] = None,
) -> dict:
    captured_at = captured_at or datetime.now(timezone.utc)
    season = current_season(team_year)
    weeks = weeks_completed(team_week, season) if season is not None else 0
    # EVERY numeric column ranks — no volatility filter. #380 excluded the
    # league-relative and rolling families here on the theory that they drift a
    # hair on every recompute and would flip a rank-boundary tie into a phantom
    # move; in practice a rank-boundary flip is a real change of order and the
    # columns it hides (the skill family, Luck, the KTC windows) are ones a
    # reader wants to hear about. The weekly AUDIT still exempts them — there the
    # question is "did a frozen historical value move", which is a different one.
    p_cols = discover_numeric_columns(player_all_time, "Player")
    t_cols = discover_numeric_columns(team_all_time, "Team")
    return {
        "meta": {
            "captured_at": captured_at.isoformat(),
            "season": season,
            "weeks_completed": weeks,
        },
        "players": _rankings_for(player_all_time, "Player", p_cols),
        "teams": _rankings_for(team_all_time, "Team", t_cols),
        "league_milestones": league_milestone_values(
            league_all_time if league_all_time is not None else pd.DataFrame()),
    }


def is_in_season(snapshot: dict) -> bool:
    return int(snapshot.get("meta", {}).get("weeks_completed", 0) or 0) >= 1


# ---------------------------------------------------------------------------
# Crossings (diff)
# ---------------------------------------------------------------------------
@dataclass
class Crossing:
    section: str        # "players" | "teams"
    column: str
    end: str            # "high" | "low"
    rank: int           # competition rank from the watched end (1-indexed)
    mover: str
    value: float
    # Arriving at a value someone already holds is JOINING a tie, not overtaking
    # anyone — "passes X" there says the opposite of what happened. A join names
    # the co-holder(s); an overtake names everyone the mover leapt (which can be
    # a whole tie at once). See _crossing_detail.
    joined: bool = False
    others: tuple = ()          # co-holders at the mover's value, when joined
    passed: tuple = ()          # entities overtaken, when not joined

    def group(self) -> str:
        return self.mover

    def detail(self) -> str:
        return _crossing_detail(self.joined, self.others, self.passed,
                                _place(self.rank, self.end), self.column, self.value)

    def sentence(self) -> str:
        # No "all-time": the section header says it, and EventCrossing — the same
        # kind of news on a different sheet — never said it. Two spellings of one
        # sentence under two identically-shaped headers was the odd part.
        return f"{self.mover} {self.detail()}."


def _column_crossings(section: str, column: str,
                      prev: Sequence[dict], curr: Sequence[dict],
                      ends: Sequence[str], window: Optional[int],
                      cap_half: bool) -> List[Crossing]:
    """Crossings within the watched end(s) of one column.

    Ranks are COMPETITION ranks over values (Change 4): a two-way tie for 1st
    makes the next distinct value 3rd, and tied rows take up the requisite number
    of the top-N slots. A mover that arrives at a value others already hold JOINS
    that tie (phrased as a join, suppressed entirely once the tie exceeds five);
    a mover that lands alone overtakes everyone that was ahead of it and is now
    behind — a whole tie at once, named in full.

    `window=None` watches the whole board (used for the 8-team league, "any
    movement in the 8"). When `cap_half` is set the window is capped at half the
    board so the top and bottom ends never overlap.
    """
    out: List[Crossing] = []
    prev_val = {e["entity"]: e["value"] for e in prev}
    curr_val = {e["entity"]: e["value"] for e in curr}
    n = len(curr)
    window = n if window is None else window
    if cap_half:
        window = min(window, max(1, n // 2))
    for end in ends:
        prev_rank = competition_ranks([e["value"] for e in prev], end)
        curr_rank = competition_ranks([e["value"] for e in curr], end)
        for mover, v in curr_val.items():
            if mover not in prev_val:
                continue
            new_rank = curr_rank[v]
            if new_rank > window:
                continue
            old_rank = prev_rank.get(prev_val[mover])
            if old_rank is None or new_rank >= old_rank:
                continue  # not improved toward this end
            others = [x for x, xv in curr_val.items()
                      if x != mover and xv == v]
            if others:
                # Joined a tie. Suppress once it exceeds five holders total.
                if len(others) >= _MAX_JOIN_TIE:
                    continue
                out.append(Crossing(section, column, end, new_rank, mover, v,
                                    joined=True, others=tuple(sorted(others))))
                continue
            # Landed alone: everyone that was ahead of the mover and is now behind
            # it got overtaken (a whole tie counts as several).
            passed = [x for x in curr_val
                      if x != mover and x in prev_val
                      and prev_rank.get(prev_val[x], n + 1) < old_rank
                      and curr_rank[curr_val[x]] > new_rank]
            if not passed:
                continue
            out.append(Crossing(section, column, end, new_rank, mover, v,
                                joined=False, passed=tuple(sorted(passed))))
    return out


def diff_snapshots(prev: dict, curr: dict) -> List[Crossing]:
    """All all-time leaderboard crossings between two snapshots, per the
    per-section rules in CROSSING_CONFIG (players top/bottom 5; teams any-of-8)."""
    crossings: List[Crossing] = []
    for section, cfg in CROSSING_CONFIG.items():
        prev_sec = prev.get(section, {})
        curr_sec = curr.get(section, {})
        for column, curr_list in curr_sec.items():
            prev_list = prev_sec.get(column)
            if not prev_list:
                continue
            crossings.extend(_column_crossings(
                section, column, prev_list, curr_list,
                cfg["ends"], cfg["window"], cfg["cap_half"],
            ))
    return crossings


# ---------------------------------------------------------------------------
# On-pace projections
# ---------------------------------------------------------------------------
@dataclass
class Projection:
    section: str        # "players" | "teams" | "league"
    entity: str
    column: str
    end: str            # "high" | "low"
    rank: int
    total: int
    projected: float
    final: bool = False  # season complete -> "finished Nth" instead of "on pace"

    def group(self) -> str:
        return "The league" if self.section == "league" else self.entity

    def detail(self) -> str:
        return f"{_place(self.rank, self.end)} {self.column} ({_fmt(self.projected)})"

    def sentence(self) -> str:
        val = _fmt(self.projected)
        if self.final:
            return (f"{self.group()} finished with the {_place(self.rank, self.end)} "
                    f"{self.column} of any season ({val}).")
        return (f"{self.group()} is on pace for {_place(self.rank, self.end)} "
                f"{self.column} this season ({val}).")


def _is_boolean(values: Sequence[float]) -> bool:
    """True if every value is 0 or 1 — a per-season flag that can't be projected
    'on pace' (e.g. #363's 'Rostered by champion?')."""
    return bool(values) and all(v in (0.0, 1.0) for v in values)


def _season_horizon(week_frame: pd.DataFrame, current: int) -> Optional[int]:
    """Full-season week count = max week seen in a completed prior season."""
    if week_frame.empty or "Year" not in week_frame.columns or "Week" not in week_frame.columns:
        return None
    years = pd.to_numeric(week_frame["Year"], errors="coerce")
    weeks = pd.to_numeric(week_frame["Week"], errors="coerce")
    prior_max = 0
    for y in sorted({int(v) for v in years.dropna().unique() if int(v) < current}):
        wk = weeks[years == y].dropna()
        if len(wk):
            prior_max = max(prior_max, int(wk.max()))
    return prior_max or None


def _project_frame(
    section: str,
    year_df: pd.DataFrame,
    entity_col: str,
    season: int,
    scale: float,
    window: int,
) -> List[Projection]:
    """Project every numeric yearly column for one sheet and keep the notable
    (top/bottom window) projections ranked against completed seasons."""
    cols = discover_numeric_columns(year_df, entity_col, extra_skip=("Year",))
    year_num = pd.to_numeric(year_df["Year"], errors="coerce")
    curr = year_df[year_num == season]
    hist = year_df[year_num < season]

    projections: List[Projection] = []
    for col in cols:
        if is_weekly_counting_stat(col):
            continue  # awards / result-flip tallies -> actual-value records path
        hist_vals = [v for v in (_to_float(x) for x in hist[col]) if v is not None]
        if len(hist_vals) < window:      # need a meaningful pool to rank against
            continue
        rate = is_rate_stat(col)
        # Project each current entity, then rank ALL entity-seasons (history +
        # this season's projections) together, by DISTINCT value, skipping any
        # value shared by more than _MAX_HIGHLIGHT_TIES (the only exclusion — this
        # is how 0/1 flags and heavily-tied stats fall out).
        proj_by_entity = []
        for _, r in curr.iterrows():
            cur = _to_float(r[col])
            if cur is None:
                continue
            entity = str(r[entity_col]) if entity_col in year_df.columns else str(season)
            proj_by_entity.append((entity, cur if rate else cur * scale))
        if not proj_by_entity:
            continue
        pool = hist_vals + [p for _, p in proj_by_entity]
        counts = _Counter(pool)
        high_rank = {v: i + 1 for i, v in enumerate(sorted(counts, reverse=True))}
        low_rank = {v: i + 1 for i, v in enumerate(sorted(counts))}
        total = len(pool)
        for entity, projected in proj_by_entity:
            if counts[projected] > _MAX_HIGHLIGHT_TIES:
                continue
            if high_rank[projected] <= window:
                projections.append(Projection(section, entity, col, "high",
                                              high_rank[projected], total, projected))
            elif low_rank[projected] <= window:
                projections.append(Projection(section, entity, col, "low",
                                              low_rank[projected], total, projected))
    return projections


def _league_window(league_year: pd.DataFrame) -> int:
    """league_year on-pace window = floor(#seasons / 3), capped at 5. With few
    seasons on record the league board is tiny, so the window shrinks with it."""
    if league_year.empty or "Year" not in league_year.columns:
        return 0
    n_seasons = pd.to_numeric(league_year["Year"], errors="coerce").dropna().nunique()
    return min(LEAGUE_WINDOW_CAP, n_seasons // 3)


def project_on_pace(
    player_year: pd.DataFrame,
    team_year: pd.DataFrame,
    league_year: pd.DataFrame,
    team_week: pd.DataFrame,
    min_week: int = MIN_YEARLY_WEEK,
) -> List[Projection]:
    """On-pace projections across player / team / league yearly sheets, per the
    per-section windows (players/teams top/bottom 5; league floor(#seasons/3)≤5).
    Weekly-counting stats (awards, result-flips) are excluded. Empty before
    `min_week` completed weeks, in the offseason, or before a completed prior
    season exists.
    """
    season = current_season(team_year)
    if season is None:
        return []
    played = weeks_completed(team_week, season)
    horizon = _season_horizon(team_week, season)
    if played < min_week or not horizon or played >= horizon:
        return []
    scale = horizon / played

    out: List[Projection] = []
    out += _project_frame("players", player_year, "Player", season, scale,
                          PROJECTION_WINDOW["players"])
    out += _project_frame("teams", team_year, "Team", season, scale,
                          PROJECTION_WINDOW["teams"])
    lw = _league_window(league_year)
    if lw >= 1 and not league_year.empty and "Year" in league_year.columns:
        out += _project_frame("league", league_year, "Year", season, scale, lw)
    return out


def pace_rank_map(projections: Sequence[Projection]) -> dict:
    """Compact {section: {stat: {entity: 'end:rank'}}} for snapshotting the
    on-pace standing, so next week can report only the ones that MOVED."""
    out: Dict[str, Dict[str, Dict[str, str]]] = {}
    for p in projections:
        out.setdefault(p.section, {}).setdefault(p.column, {})[p.entity] = f"{p.end}:{p.rank}"
    return out


def diff_pace(prior_pace: dict, projections: Sequence[Projection]) -> List[Projection]:
    """On-pace projections whose notable rank CHANGED since last week (or newly
    entered the top/bottom window). An entity that unchanged its standing is
    silent — this is what keeps the over-inclusive digest to a readable size."""
    changed: List[Projection] = []
    for p in projections:
        prior = prior_pace.get(p.section, {}).get(p.column, {}).get(p.entity)
        if prior != f"{p.end}:{p.rank}":
            changed.append(p)
    return changed


# ---------------------------------------------------------------------------
# Yearly records (for the weekly-counting stats that DON'T get on-pace)
# ---------------------------------------------------------------------------
# Weekly-counting stats (awards, result-flips) can't be projected "on pace", so
# instead we alert when the current season's ACTUAL value sets a new all-time
# single-season record — the most that stat has ever been in ANY season. Booleans
# are excluded (a 0/1 "record" is meaningless — those surface via all-time counts).
@dataclass
class YearlyRecord:
    section: str        # "players" | "teams" | "league"
    entity: str
    column: str
    value: float

    # A record is only emitted when the value beats every completed season
    # (`_records_for_frame`), so it is 1st place on that stat's all-time
    # single-season board — by construction, not by convention. Saying so keeps
    # it sorting alongside every other 1st place instead of behind them; the
    # prose already carries the claim ("most in any season"), which is why the
    # sentence doesn't repeat it as an ordinal.
    rank: int = 1

    def group(self) -> str:
        return "The league" if self.section == "league" else self.entity

    def detail(self) -> str:
        return f"{self.column} ({_fmt(self.value)})"

    def sentence(self) -> str:
        return (f"{self.group()} sets a new single-season record for {self.column} "
                f"({_fmt(self.value)}) — most in any season.")

    def line(self) -> str:
        # The header already says "New single-season records"; saying it again
        # and then adding "most in any season" states one fact three times.
        return f"{self.group()}: {self.detail()} — most in any season."


def _records_for_frame(section: str, year_df: pd.DataFrame,
                       entity_col: str, season: int) -> List[YearlyRecord]:
    if year_df.empty or "Year" not in year_df.columns:
        return []
    year_num = pd.to_numeric(year_df["Year"], errors="coerce")
    curr = year_df[year_num == season]
    hist = year_df[year_num < season]
    out: List[YearlyRecord] = []
    for col in discover_numeric_columns(year_df, entity_col, extra_skip=("Year",)):
        if not is_weekly_counting_stat(col):
            continue  # records here are only for the not-on-pace weekly stats
        hist_vals = [v for v in (_to_float(x) for x in hist[col]) if v is not None]
        if not hist_vals:
            continue  # need completed seasons to define a record to beat
        pairs = [(str(r[entity_col]) if entity_col in year_df.columns else str(season),
                  _to_float(r[col])) for _, r in curr.iterrows()]
        pairs = [(e, v) for e, v in pairs if v is not None]
        if not pairs:
            continue
        hist_max = max(hist_vals)
        curr_max = max(v for _, v in pairs)
        if curr_max <= hist_max:
            continue  # no new record this season
        holders = [e for e, v in pairs if abs(v - curr_max) < 1e-9]
        if len(holders) > _MAX_HIGHLIGHT_TIES:
            continue  # >5 tied for the "record" -> not notable (the >5-tied rule)
        for e in holders:
            out.append(YearlyRecord(section, e, col, curr_max))
    return out


def yearly_records(player_year: pd.DataFrame, team_year: pd.DataFrame,
                   league_year: pd.DataFrame, team_week: pd.DataFrame,
                   min_week: int = MIN_YEARLY_WEEK,
                   season: Optional[int] = None) -> List[YearlyRecord]:
    """New all-time single-season records set by weekly-counting stats. Defaults
    to the current season (withheld until `min_week` completed weeks); pass an
    explicit `season` (e.g. a finished season) to skip the week gate."""
    if season is None:
        season = current_season(team_year)
        if season is None or weeks_completed(team_week, season) < min_week:
            return []
    out: List[YearlyRecord] = []
    out += _records_for_frame("players", player_year, "Player", season)
    out += _records_for_frame("teams", team_year, "Team", season)
    if not league_year.empty and "Year" in league_year.columns:
        out += _records_for_frame("league", league_year, "Year", season)
    return out


def record_value_map(records: Sequence[YearlyRecord]) -> dict:
    """{section: {stat: record_value}} snapshot so next week only re-reports a
    record when it's been beaten/extended, not every week it stands."""
    out: Dict[str, Dict[str, float]] = {}
    for r in records:
        out.setdefault(r.section, {})[r.column] = r.value
    return out


def diff_records(prior_map: dict, records: Sequence[YearlyRecord]) -> List[YearlyRecord]:
    """Records that are newly set or have grown past last week's record value."""
    changed: List[YearlyRecord] = []
    for r in records:
        prev = prior_map.get(r.section, {}).get(r.column)
        if prev is None or r.value > prev + 1e-9:
            changed.append(r)
    return changed


# ---------------------------------------------------------------------------
# Weekly single-week highlights (the WEEKLY sheets: player/team/league_week)
# ---------------------------------------------------------------------------
# Rank the just-completed week's single-week values against EVERY week ever, and
# surface the ones landing in the top/bottom `WINDOW` — "best/worst single week
# of all time" alerts. This is how the weekly sheets get directly involved in the
# digest (they otherwise only feed the year/all-time rollups). Booleans (per-week
# award flags) are skipped — their tallies show via the year/all-time paths.

# A single-week value shared by more than this many week-rows is too common to be
# a "record" (e.g. the pile of 0s on percentile / streak columns, or a routinely
# tied max), so it's skipped on BOTH ends. Genuine extremes are near-unique.
_MAX_HIGHLIGHT_TIES = 5


# Two spellings, on purpose:
#   sentence()  stands alone — the lede quotes it, and a lede that needs its
#               section header to make sense is no use at the top of the email.
#   line()      is what the SECTION prints, where the header has already said
#               where you are. Default: the same string. Overridden only where
#               the standalone framing would restate the header word for word.
@dataclass
class WeeklyHighlight:
    section: str        # "players" | "teams" | "league"
    entity: str
    column: str
    end: str            # "high" | "low"
    rank: int           # among every DISTINCT single-week value on record
    value: float

    def group(self) -> str:
        return "The league" if self.section == "league" else self.entity

    def detail(self) -> str:
        return f"{self.column} ({_fmt(self.value)}) — {_place(self.rank, self.end)} ever"

    def sentence(self) -> str:
        return (f"{self.group()}'s {self.column} this week ({_fmt(self.value)}) is the "
                f"{_place(self.rank, self.end)} single week ever.")

    def line(self) -> str:
        # "…'s Points this week (55) is the highest single week ever" under a
        # header that already reads "Single-week records (this week)".
        return f"{self.group()}'s {self.detail()}."


def latest_completed_week(team_week: pd.DataFrame, season: int) -> Optional[int]:
    if team_week.empty or "Year" not in team_week.columns or "Week" not in team_week.columns:
        return None
    sub = team_week[pd.to_numeric(team_week["Year"], errors="coerce") == season]
    weeks = pd.to_numeric(sub["Week"], errors="coerce").dropna()
    return int(weeks.max()) if len(weeks) else None


def latest_completed_season_week(team_week: pd.DataFrame) -> Optional[tuple]:
    """The most recent completed (season, week) across ALL seasons — i.e. the
    last week that has games on record (the championship week of the latest
    finished season in the offseason). Drives the 'most recent digest' replica."""
    if team_week.empty or "Year" not in team_week.columns:
        return None
    years = pd.to_numeric(team_week["Year"], errors="coerce").dropna()
    if not len(years):
        return None
    season = int(years.max())
    week = latest_completed_week(team_week, season)
    return (season, week) if week else None


def _highlights_for_frame(section: str, wk_df: pd.DataFrame, entity_col: str,
                          season: int, week: int, window: int,
                          sheet: str = "") -> List[WeeklyHighlight]:
    if wk_df.empty or "Year" not in wk_df.columns or "Week" not in wk_df.columns:
        return []
    year = pd.to_numeric(wk_df["Year"], errors="coerce")
    wknum = pd.to_numeric(wk_df["Week"], errors="coerce")
    this_week = wk_df[(year == season) & (wknum == week)]
    if this_week.empty:
        return []
    has_entity = entity_col in wk_df.columns

    mirrored = mirrored_columns(wk_df, sheet)
    out: List[WeeklyHighlight] = []
    for col in discover_numeric_columns(wk_df, entity_col):
        all_vals = rankable_series(wk_df, col, col in mirrored).tolist()
        if len(all_vals) < window:
            continue
        # Both ends (some stats go negative, so "lowest ever" is meaningful).
        # Rank by DISTINCT value so ties share a rank; the ONLY exclusion is a
        # value shared by more than _MAX_HIGHLIGHT_TIES rows (that's how booleans
        # and heavily-tied cumulative extremes fall out — per the >5-tied rule).
        counts = _Counter(all_vals)
        # Competition ("1224") ranks so tied weeks take up the requisite slots:
        # a two-way tie for the record makes the next value the 3rd-best ever.
        high_rank = competition_ranks(all_vals, "high")
        low_rank = competition_ranks(all_vals, "low")
        for _, r in this_week.iterrows():
            v = _to_float(r[col])
            # `v not in counts` covers the losing half of a mirrored column: the
            # pool holds only the positive side, so the loser's -M isn't ranked
            # (the same fact is already reported from the winner's row).
            if v is None or v not in counts or counts[v] > _MAX_HIGHLIGHT_TIES:
                continue
            entity = str(r[entity_col]) if has_entity else "The league"
            if high_rank[v] <= window:
                out.append(WeeklyHighlight(section, entity, col, "high", high_rank[v], v))
            elif low_rank[v] <= window:
                out.append(WeeklyHighlight(section, entity, col, "low", low_rank[v], v))
    return out


def weekly_highlights(player_week: pd.DataFrame, team_week: pd.DataFrame,
                      league_week: pd.DataFrame, team_year: pd.DataFrame,
                      window: int = WINDOW,
                      season: Optional[int] = None,
                      week: Optional[int] = None) -> List[WeeklyHighlight]:
    """Top/bottom-`window` single-week performances in a completed week, ranked
    against every week on record. Defaults to the current season's latest week
    (empty in the offseason); pass explicit season/week for a past week."""
    if season is None:
        season = current_season(team_year)
    if season is None:
        return []
    if week is None:
        week = latest_completed_week(team_week, season)
    if not week:
        return []
    out: List[WeeklyHighlight] = []
    out += _highlights_for_frame("players", player_week, "Player", season, week, window,
                                 sheet="player_week")
    out += _highlights_for_frame("teams", team_week, "Team", season, week, window,
                                 sheet="team_week")
    out += _highlights_for_frame("league", league_week, "Year", season, week, window,
                                 sheet="league_week")
    return out


# ---------------------------------------------------------------------------
# All-time boards (every row-level sheet)
# ---------------------------------------------------------------------------
# A sheet's rows are its records: a pick, a trade, a transaction — but equally
# one player's season, one team's week. Every numeric column of every such sheet
# is ranked over EVERY row of that sheet ever, and the top/bottom `WINDOW` are
# snapshotted. Week over week the board is diffed and read out in the same
# "X passes Y for Nth-highest …" sentence as the player / team all-time boards,
# because it is the same news: a place on a leaderboard changed hands.
#
# Covering every season (not just the in-progress one) is what makes a recompute
# of HISTORY reportable. A rolling KTC window crossing an anniversary, or a
# formula change, re-values a 2023 trade into the all-time O-Score top 5 — the row
# that moved is a past-season row, and a board holding only the current season's
# rows produced no item at all.


@dataclass
class EventHighlight:
    sheet: str          # "picks" | "trades" | "add_drops"
    label: str          # human name of the event (e.g. "2025 pick 1.01 (…)")
    column: str
    end: str            # "high" | "low"
    rank: int
    value: float
    key: str = ""       # stable row identity (see _event_row_key); NOT the label

    def group(self) -> str:
        return self.label

    def detail(self) -> str:
        return (f"{self.column} of {_fmt(self.value)} — "
                f"{_place(self.rank, self.end)} of any {self.sheet[:-1]} ever")

    def sentence(self) -> str:
        return (f"{self.label}: {self.column} of {_fmt(self.value)} — "
                f"{_place(self.rank, self.end)} of any {self.sheet[:-1]} ever.")


def _event_cell(row, col) -> str:
    v = row.get(col) if hasattr(row, "get") else None
    return "" if v is None or (isinstance(v, float) and math.isnan(v)) else str(v)


# How many assets a trade label names before it stops listing them. The longest
# deal on record received 12 (330 characters); a subject line's worth is enough
# to recognise the deal, and the sheet holds the full list.
_LABEL_ASSETS = 3


def _asset_summary(raw: str) -> str:
    """"A; B; C; D" -> "A, B, C +1 more" — the assets a side of a deal received."""
    parts = [a.strip() for a in str(raw).split(";") if a.strip()]
    if not parts:
        return ""
    shown = ", ".join(parts[:_LABEL_ASSETS])
    extra = len(parts) - _LABEL_ASSETS
    return f"{shown} +{extra} more" if extra > 0 else shown


def _board_label(sheet: str, row) -> str:
    """How a row is named in the email. Season / week rows are named by entity and
    when; event rows name what actually moved (the assets)."""
    def g(c):
        return _event_cell(row, c)
    # Dates carry a timestamp for uniqueness; the label only needs the day. (The
    # row KEY still uses the full value — see _board_row_key.)
    day = lambda c: g(c)[:10]
    if sheet == "player_year":
        return f"{g('Player')} {g('Year')}".strip()
    if sheet == "team_year":
        return f"{g('Team')} {g('Year')}".strip()
    if sheet == "league_year":
        return f"the {g('Year')} season".strip()
    if sheet == "player_week":
        return f"{g('Player')} {g('Year')} week {g('Week')}".strip()
    if sheet == "team_week":
        return f"{g('Team')} {g('Year')} week {g('Week')}".strip()
    if sheet == "league_week":
        return f"{g('Year')} week {g('Week')}".strip()
    if sheet == "picks":
        return f"{g('Year')} pick {g('Number')} ({g('Player Picked')})".strip()
    if sheet == "trades":
        # Name what the team got: "whose trade" alone doesn't say what moved, and
        # a team can make several deals on one day.
        got = _asset_summary(g("Assets received"))
        head = f"{g('Team')}'s {day('Date')} trade"
        return f"{head} for {got}" if got else head
    if sheet == "add_drops":
        added, dropped = g("Player Added"), g("Player Dropped")
        # The date disambiguates: one team can pick the same player up twice, and
        # two board lines reading "LWebs53's move for Jeff Wilson" are unreadable.
        head = f"{g('Team')}'s {day('Date')}"
        if added:
            return f"{head} move for {added}".strip()
        return f"{head} drop of {dropped}".strip() if dropped else f"{head} move"
    if sheet == "player_additions":
        # "<Team>'s <date> <Waiver|Trade|Draft…> pickup of <Player>"
        kind = (g("Addition type") or "").lower() or "pickup"
        return f"{g('Team')}'s {day('Date')} {kind} of {g('Player')}".strip()
    return sheet


# The board's row identity. NOT the label — a label is written for a human and
# repeats (the same team picking the same player up twice), which would merge two
# distinct rows into one place on the board and manufacture movement between them
# on every diff. NOT the row index either: inserting one current-season row
# renumbers every later one, which is the same trap the "Link to …" columns fall
# into. `ids` in _BOARD_SHEETS are the sheets' natural keys.
def _board_row_key(sheet: str, row) -> str:
    cols = _BOARD_SHEETS.get(sheet, {}).get("ids")
    if not cols:
        return _board_label(sheet, row)
    return sheet + "|" + "|".join(_event_cell(row, c) for c in cols)


# Every row-level sheet gets a board. A sheet's "events" are its rows: a pick, a
# trade, a transaction — but also one player's season, one team's week. Ranking
# all of them against every row of that sheet ever is what makes the answer to
# "did anything move into the top 5 of anything?" a single mechanism instead of
# one special case per sheet. `entity` is the column discover_numeric_columns
# treats as the row's name (not a stat); `ids` are the natural key; `title` names
# the section in the email.
_BOARD_SHEETS = {
    "player_year":  {"entity": "Player", "ids": ("Player", "Year"),
                     "title": "player seasons"},
    "team_year":    {"entity": "Team", "ids": ("Team", "Year"),
                     "title": "team seasons"},
    "league_year":  {"entity": "Year", "ids": ("Year",),
                     "title": "league seasons"},
    "player_week":  {"entity": "Player", "ids": ("Player", "Year", "Week"),
                     "title": "player weeks"},
    "team_week":    {"entity": "Team", "ids": ("Team", "Year", "Week"),
                     "title": "team weeks"},
    "league_week":  {"entity": "Year", "ids": ("Year", "Week"),
                     "title": "league weeks"},
    "picks":        {"entity": "Year", "ids": ("Year", "Number"),
                     "title": "draft picks"},
    "trades":       {"entity": "Season", "ids": ("Team", "Date", "Team's traded with 1"),
                     "title": "trades"},
    "add_drops": {"entity": "Season",
                     "ids": ("Team", "Date", "Player Added", "Player Dropped"),
                     "title": "add/drops"},
    "player_additions": {"entity": "Player",
                     "ids": ("Player", "Team", "Date", "Addition type"),
                     "title": "player additions"},
}


def board_highlights(df: pd.DataFrame, sheet: str, window: int = WINDOW,
                     max_ties: int = _MAX_HIGHLIGHT_TIES) -> List[EventHighlight]:
    """The top/bottom-`window` rows of every numeric column on one sheet, ranked
    against every row of that sheet ever (mirrored columns: positive side only).

    Ranks are COMPETITION ranks over values (Change 4): tied rows take up the
    requisite number of the top-N slots, so a two-way tie for 1st makes the next
    value 3rd. A value shared by more than `max_ties` rows is not a record and is
    left off the board — but it still occupies its slots, so the places below it
    keep their numbering."""
    cfg = _BOARD_SHEETS.get(sheet)
    if cfg is None or df is None or df.empty:
        return []
    mirrored = mirrored_columns(df, sheet)
    out: List[EventHighlight] = []
    for col in discover_numeric_columns(df, cfg["entity"]):
        s = rankable_series(df, col, col in mirrored)
        if len(s) < window:
            continue
        counts = s.value_counts()
        vals = s.tolist()
        hi = competition_ranks(vals, "high")
        lo = competition_ranks(vals, "low")
        # value -> (end, rank); the high end wins when a value qualifies at both
        # (a short board where the top and bottom five overlap).
        wanted: Dict[float, tuple] = {}
        for v, r in hi.items():
            if r <= window and counts[v] <= max_ties:
                wanted[v] = ("high", r)
        for v, r in lo.items():
            if v not in wanted and r <= window and counts[v] <= max_ties:
                wanted[v] = ("low", r)
        if not wanted:
            continue
        for idx, value in s[s.isin(wanted)].items():
            row = df.loc[idx]
            end, rank = wanted[value]
            out.append(EventHighlight(sheet, _board_label(sheet, row), col,
                                      end, rank, float(value),
                                      _board_row_key(sheet, row)))
    return out


def all_board_highlights(frames: dict, window: int = WINDOW) -> List[EventHighlight]:
    """Every board across every sheet that has rows to rank — what the weekly
    digest snapshots and diffs."""
    out: List[EventHighlight] = []
    for sheet in _BOARD_SHEETS:
        out += board_highlights(frames.get(sheet, pd.DataFrame()), sheet, window)
    return out


# ---------------------------------------------------------------------------
# Mirror detection for the phrasing catalog
# ---------------------------------------------------------------------------
# The email itself no longer needs this: a mirrored column is detected by
# is_mirrored_column and ranked on its positive side like any other. This
# per-matchup form survives only to LABEL such columns in the phrasing catalog.
def two_sided_columns(df: pd.DataFrame, entity_col: str, opp_col: str,
                      id_cols: Sequence[str]) -> List[str]:
    """Numeric columns that are genuinely two-sided: for most events the pair's
    two rows hold mirror values (a ≈ -b). Detected from the data, no name list."""
    if df is None or df.empty or opp_col not in df.columns:
        return []
    out: List[str] = []
    for col in discover_numeric_columns(df, entity_col):
        groups: Dict[tuple, list] = {}
        for _, r in df.iterrows():
            v = _to_float(r[col])
            if v is None:
                continue
            a, b = str(r[entity_col]), str(r.get(opp_col) or "")
            if not b:
                continue
            key = tuple(str(r.get(c, "")) for c in id_cols) + tuple(sorted([a, b]))
            groups.setdefault(key, []).append(v)
        mirror = tot = 0
        for vs in groups.values():
            if len(vs) != 2:
                continue
            mag = max(abs(vs[0]), abs(vs[1]))
            if mag <= 1e-6:
                continue  # a 0/0 pair is trivially "mirrored"; not a real two-sided stat
            tot += 1
            if abs(vs[0] + vs[1]) <= 1e-6 + 0.01 * mag:
                mirror += 1
        if tot >= 3 and mirror / tot >= 0.8:
            out.append(col)
    return out

@dataclass
class EventCrossing:
    """One event overtaking (or joining) a place on an all-time event board.

    Phrased exactly like an all-time player/team `Crossing`. A mover that lands
    alone overtakes whoever held the slot it took — a whole tie at once, named in
    full ("passes X and Y for lowest"). A mover that arrives at a value others
    still hold JOINS the tie instead (named when two-way, summarised otherwise,
    suppressed once the tie exceeds five). Only the mover is reported.
    """
    sheet: str          # "picks" | "trades" | "add_drops"
    label: str          # the mover, named; identity is the row key
    column: str
    end: str            # "high" | "low"
    rank: int
    value: Optional[float]
    joined: bool = False
    others: tuple = ()          # co-holders at the mover's value, when joined
    passed: tuple = ()          # entities overtaken, when not joined

    def group(self) -> str:
        return self.label

    def detail(self) -> str:
        return _crossing_detail(self.joined, self.others, self.passed,
                                _place(self.rank, self.end), self.column, self.value)

    def sentence(self) -> str:
        return f"{self.label} {self.detail()}."


def event_board(events: Sequence[EventHighlight]) -> list:
    """The snapshot payload: every place on every event board, with its rank, in
    a stable order so the committed snapshot diffs cleanly week to week."""
    return sorted(
        ({"sheet": e.sheet, "key": e.key, "label": e.label, "column": e.column,
          "end": e.end, "rank": e.rank, "value": e.value} for e in events),
        key=lambda d: (d["sheet"], d["column"], d["end"], d["rank"], d["key"]))


def _prior_board(prior_board) -> Optional[Dict[tuple, dict]]:
    """Prior board as (sheet, column, end) -> {rank -> place, keys -> {key: rank}}.
    None when it can't be read as a board — including the pre-board snapshot
    format (a list of "sheet|label|col|end:rank" strings), which the caller then
    treats as "no prior", re-baselining in silence instead of reporting the whole
    board as new."""
    if not prior_board:
        return None
    out: Dict[tuple, dict] = {}
    for d in prior_board:
        if not isinstance(d, dict):
            return None
        try:
            slot = out.setdefault((d["sheet"], d["column"], d["end"]),
                                  {"by_rank": {}, "by_key": {}})
            rank = int(d["rank"])
            slot["by_key"][d["key"]] = rank
            # Every holder of a rank last week, so overtaking a whole tie names
            # all of them (Change 4).
            slot["by_rank"].setdefault(rank, []).append(d.get("label", d["key"]))
        except (KeyError, TypeError, ValueError):
            return None
    return out


def diff_events(prior_board, events: Sequence[EventHighlight]) -> List[EventCrossing]:
    """Overtakes on the event boards since `prior_board`.

    An event is reported when it now holds a place nearer the watched end than it
    held last week — including arriving from off the board entirely, which is how
    a re-valued historical row shows up. `passed` is whoever held that place last
    week; with no one there (the board was shorter), there is no overtake to
    report and the event is skipped.

    A place can also be JOINED rather than taken: ranks are competition ranks
    over values, so co-occupants of a rank hold the same value. If anyone else is
    still standing on the rank the mover arrived at, nobody was displaced and the
    move is a tie-join — named when two-way, summarised for three-to-five, and
    suppressed once the tie exceeds five. Landing alone overtakes every prior
    holder of the slot taken (a whole tie counts as several), named in full."""
    prior = _prior_board(prior_board)
    if prior is None:
        return []
    # Who else stands on each place NOW. Built once, not per event: on a busy
    # week this walks several thousand board places.
    co: Dict[tuple, Dict[int, List[str]]] = {}
    for e in events:
        co.setdefault((e.sheet, e.column, e.end), {}).setdefault(e.rank, []).append(e.key)
    label_of = {(e.sheet, e.column, e.end, e.key): e.label for e in events}
    out: List[EventCrossing] = []
    for e in events:
        slot = prior.get((e.sheet, e.column, e.end))
        if not slot:
            continue
        was = slot["by_key"].get(e.key)
        if was is not None and e.rank >= was:
            continue                       # unmoved, or pushed down by someone else
        ck = (e.sheet, e.column, e.end)
        other_keys = [k for k in co[ck][e.rank] if k != e.key]
        if other_keys:
            # Joined a tie. Suppress once it exceeds five holders total.
            if len(other_keys) >= _MAX_JOIN_TIE:
                continue
            others = sorted(label_of.get((e.sheet, e.column, e.end, k), k)
                            for k in other_keys)
            if e.label in others:
                # A different row of the SAME entity already held the place; that
                # is not news about the entity.
                continue
            out.append(EventCrossing(e.sheet, e.label, e.column, e.end, e.rank,
                                     e.value, joined=True, others=tuple(others)))
            continue
        # Landed alone: overtook every prior holder of the slot it now occupies.
        passed = [lbl for lbl in slot["by_rank"].get(e.rank, []) if lbl != e.label]
        if not passed:
            continue
        out.append(EventCrossing(e.sheet, e.label, e.column, e.end, e.rank,
                                 e.value, joined=False, passed=tuple(sorted(passed))))
    return out


# ---------------------------------------------------------------------------
# League all-time milestones (single-row sheet -> no leaderboard)
# ---------------------------------------------------------------------------
@dataclass
class Milestone:
    stat: str
    value: float
    milestone: float

    def sentence(self) -> str:
        return (f"League {self.stat} passes {_fmt(self.milestone)} "
                f"(now {_fmt(self.value)}).")

    def line(self) -> str:
        # Under "League milestones", the leading "League" is the header again.
        return f"{self.stat} passes {_fmt(self.milestone)} (now {_fmt(self.value)})."


def league_milestone_values(league_all_time: pd.DataFrame) -> Dict[str, float]:
    """Current value of each major league_all_time total (single-row sheet)."""
    out: Dict[str, float] = {}
    if league_all_time is None or league_all_time.empty:
        return out
    row = league_all_time.iloc[0]
    for stat in MAJOR_LEAGUE_STATS:
        if stat in league_all_time.columns:
            v = _to_float(row[stat])
            if v is not None:
                out[stat] = v
    return out


def _round_step(v: float) -> Optional[float]:
    """Round-number granularity for milestones: the value's order of magnitude
    (e.g. 49,000 -> 10,000, so milestones fall on 40k / 50k / 60k)."""
    if v <= 0:
        return None
    return float(10 ** int(math.floor(math.log10(v))))


def milestone_crossings(prev_vals: Dict[str, float],
                        curr_vals: Dict[str, float]) -> List[Milestone]:
    """Major league totals that crossed a round number since last week."""
    out: List[Milestone] = []
    for stat, cur in curr_vals.items():
        prev = prev_vals.get(stat)
        if prev is None or cur is None or cur <= prev:
            continue
        step = _round_step(cur)
        if not step:
            continue
        crossed = math.floor(cur / step) * step   # largest round number <= cur
        if crossed > prev and crossed > 0:
            out.append(Milestone(stat, cur, crossed))
    return out


# ---------------------------------------------------------------------------
# Phrasing catalog (the reviewable "how every stat is phrased" CSV)
# ---------------------------------------------------------------------------
def phrasing_catalog(
    player_all_time: pd.DataFrame,
    team_all_time: pd.DataFrame,
    player_year: pd.DataFrame,
    team_year: pd.DataFrame,
    league_year: pd.DataFrame,
    league_all_time: Optional[pd.DataFrame] = None,
    player_week: Optional[pd.DataFrame] = None,
    team_week: Optional[pd.DataFrame] = None,
    league_week: Optional[pd.DataFrame] = None,
    picks: Optional[pd.DataFrame] = None,
    trades: Optional[pd.DataFrame] = None,
    add_drops: Optional[pd.DataFrame] = None,
    player_additions: Optional[pd.DataFrame] = None,
) -> List[dict]:
    """One row per (sheet, stat) describing exactly how a change is phrased."""
    rows: List[dict] = []

    def _add(sheet, stat, scope, scale, rise, fall):
        rows.append({"sheet": sheet, "stat": stat, "scope": scope, "scale": scale,
                     "phrase_when_rises": rise, "phrase_when_falls": fall})

    def _board_rows(sheet, df):
        """Every numeric column of a row-level sheet, ranked over every row ever."""
        if df is None or df.empty or sheet not in _BOARD_SHEETS:
            return
        mirrored = mirrored_columns(df, sheet)
        for col in discover_numeric_columns(df, _BOARD_SHEETS[sheet]["entity"]):
            note = " — mirrored, ranked on its positive side only" if col in mirrored else ""
            _add(sheet, col, f"all-time board (top/bottom 5 of every row ever{note})", "n/a",
                 f"<row> passes <other> for <N>th-highest {col} (<value>).",
                 f"<row> passes <other> for <N>th-lowest {col} (<value>).")

    def _weekly_rows(sheet, df, entity_col, who):
        if df is None or df.empty:
            return
        mirrored = mirrored_columns(df, sheet)
        for col in discover_numeric_columns(df, entity_col):
            if col in mirrored:
                _add(sheet, col, "single-week record (mirrored: positive side only)", "n/a",
                     f"{who}'s {col} this week (<value>) is the <N>th-highest single week ever.",
                     f"{who}'s {col} this week (<value>) is the <N>th-closest to zero ever.")
                continue
            _add(sheet, col, "single-week record (top/bottom 5 of all weeks ever)", "n/a",
                 f"{who}'s {col} this week (<value>) is the <N>th-highest single week ever.",
                 f"{who}'s {col} this week (<value>) is the <N>th-lowest single week ever.")

    def _crossing_rows(sheet, df, entity_col, who, scope):
        for col in discover_numeric_columns(df, entity_col):
            _add(sheet, col, scope, "n/a",
                 f"{who} passes <other> for <N>th-highest {col} all-time (<value>).",
                 f"{who} passes <other> for <N>th-lowest {col} all-time (<value>).")

    def _pace_rows(sheet, df, entity_col, who, window_note):
        for col in discover_numeric_columns(df, entity_col, extra_skip=("Year",)):
            if is_weekly_counting_stat(col):
                # Weekly-counting (awards, result-flips) can't be projected, so
                # they alert when the season's actual value sets a new all-time
                # single-season record instead.
                _add(sheet, col, "yearly record (new single-season high, any year)", "n/a",
                     f"{who} sets a new single-season record for {col} (<value>) — most in any season.",
                     "")
                continue
            scale = "as-is (rate/level)" if is_rate_stat(col) else "scaled by weeks played"
            _add(sheet, col, f"yearly on-pace (from week {MIN_YEARLY_WEEK}; {window_note})", scale,
                 f"{who} is on pace for <N>th-highest {col} this season (<value>).",
                 f"{who} is on pace for <N>th-lowest {col} this season (<value>).")

    # player_all_time: top/bottom 5. team_all_time: any movement among the 8.
    _crossing_rows("player_all_time", player_all_time, "Player", "<player>",
                   "all-time change (top/bottom 5)")
    _crossing_rows("team_all_time", team_all_time, "Team", "<team>",
                   "all-time change (any movement among the 8)")

    _pace_rows("player_year", player_year, "Player", "<player>", "top/bottom 5")
    _pace_rows("team_year", team_year, "Team", "<team>", "top/bottom 5")
    _pace_rows("league_year", league_year, "Year", "The league",
               "top/bottom floor(#seasons/3), capped at 5")

    # Weekly sheets also carry the this-week records, on top of their boards.
    _weekly_rows("player_week", player_week, "Player", "<player>")
    _weekly_rows("team_week", team_week, "Team", "<team>")
    _weekly_rows("league_week", league_week, "Year", "The league")

    # Every row-level sheet is on an all-time board: seasons, weeks, and events.
    for _sheet, _df in (("player_year", player_year), ("team_year", team_year),
                        ("league_year", league_year), ("player_week", player_week),
                        ("team_week", team_week), ("league_week", league_week),
                        ("picks", picks), ("trades", trades),
                        ("add_drops", add_drops),
                        ("player_additions", player_additions)):
        _board_rows(_sheet, _df)

    # league_all_time: milestones only (single-row sheet, no leaderboard).
    if league_all_time is not None and not league_all_time.empty:
        for col in MAJOR_LEAGUE_STATS:
            if col in league_all_time.columns:
                _add("league_all_time", col, "milestone (round-number crossing)", "n/a",
                     f"League {col} passes <round number> (now <value>).", "")
    return rows


def write_phrasing_csv(path: Path, rows: Sequence[dict]) -> None:
    df = pd.DataFrame(rows, columns=[
        "sheet", "stat", "scope", "scale", "phrase_when_rises", "phrase_when_falls",
    ])
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


# ---------------------------------------------------------------------------
# HTML render
# ---------------------------------------------------------------------------
def _section_html(title: str, lines: Sequence[str]) -> str:
    if not lines:
        return ""
    items = "\n".join(f"      <li>{ln}</li>" for ln in lines)
    return (
        f'  <h2 style="font:600 18px/1.3 system-ui,sans-serif;'
        f'margin:24px 0 8px;color:#1a2b3c;">{title}</h2>\n'
        f'    <ul style="margin:0;padding-left:20px;'
        f'font:15px/1.5 system-ui,sans-serif;color:#333;">\n{items}\n    </ul>\n'
    )


# Reading order inside a section: PLACE first, then how much the stat matters.
# A 1st-place move is the only place anyone remembers, so every 1st comes before
# every 2nd whatever it is on; within one place, the stats the league argues
# about come before the diagnostics. `stat_relevance` is the lede's own table —
# the summary at the top and the list below it should agree about what matters,
# and two tables would drift apart.
#
# The only placeless item is a league milestone — a threshold crossing, not a
# position on a board — so it sorts last on place, which inside the milestone
# section (its only home) just means it orders by relevance. Everything else
# carries a real place, single-season records included: those are 1st by
# construction, and treating them as placeless used to sink the strongest claim
# in the email below every 5th-place shuffle it shared a section with.
#
# The trailing key parts only make the order stable: an email that reshuffled
# equal items between builds would show up as movement in the audit's diff.
_NO_PLACE = 99


def _order_key(item) -> tuple:
    rank = getattr(item, "rank", None)
    place = int(rank) if isinstance(rank, int) else _NO_PLACE
    # Milestones name their stat `stat`, everything else names it `column`.
    column = str(getattr(item, "column", None) or getattr(item, "stat", "") or "")
    return (place, -stat_relevance(column), column, item.sentence())


def _ucfirst(text: str) -> str:
    """Capitalise the first letter and nothing else — `str.capitalize` lowercases
    the rest, which turns "highest Number of Add/Drops" into "…number…"."""
    return text[:1].upper() + text[1:] if text else text


def _line_of(item) -> str:
    """The item as the SECTION prints it — `line()` where it differs from
    `sentence()`, which is only where the standalone framing restates the
    header."""
    return getattr(item, "line", item.sentence)()


def _label_is_the_header(title: str, group: str) -> bool:
    """True when a section is one entity's and the header already names it.

    Only fires on the league sections, by construction: "Season-long results —
    league" holds nothing but "The league", so labelling its bullets "The
    league:" prints the header a second time. A teams section suffixed "teams"
    never matches an entity called "Oliverwkw"."""
    suffix = title.rsplit("—", 1)[-1].strip().lower().rstrip("s")
    name = group.strip().lower()
    name = name[4:] if name.startswith("the ") else name
    return bool(suffix) and suffix == name


def _grouped_section_html(title: str, items: Sequence) -> str:
    """Group items by their .group() so one entity's many items read as
    "<entity>:" + an indented sub-list, instead of an endless flat list. A group
    with a single item stays inline (its full line()).

    The label is the bare entity and a colon. It used to carry a verb — "made
    these all-time moves", "had these single-week records" — which was the
    section header said twice, one line apart. The sub-list's own wording
    already supplies the verb where one is needed.

    A group stays together and takes the position of its BEST item: breaking one
    up to interleave its 3rd-place move with someone else's would cost the reader
    the one thing the grouping buys them — seeing everything one entity did in a
    single place."""
    if not items:
        return ""
    groups: "Dict[str, list]" = {}
    for it in items:
        groups.setdefault(it.group(), []).append(it)
    ordered = []
    for g, its in groups.items():
        its.sort(key=_order_key)
        ordered.append((_order_key(its[0]), g, its))
    ordered.sort(key=lambda t: t[0])
    lines = []
    for _key, g, its in ordered:
        if _label_is_the_header(title, g):
            # One entity, already named by the header: its items are the section.
            # Nesting them under an empty label would print a bullet with nothing
            # in it and indent everything below it for no reason.
            lines.extend(_ucfirst(i.detail()) + "." for i in its)
        elif len(its) == 1:
            lines.append(_line_of(its[0]))
        else:
            sub = "".join(
                f'<li style="margin:0;">{i.detail()}</li>' for i in its)
            lines.append(
                f'{g}:'
                f'<ul style="margin:2px 0 6px;padding-left:20px;color:#555;">{sub}</ul>')
    return _section_html(title, lines)


def _proj_lines(projections: Sequence[Projection], section: str) -> List[str]:
    return [p.sentence() for p in projections if p.section == section]


def _meta_date(meta: dict) -> Optional[str]:
    """The snapshot's capture date as "August 4, 2026", or None if unparseable."""
    try:
        dt = datetime.fromisoformat(str(meta.get("captured_at") or ""))
    except ValueError:
        return None
    return f"{dt:%B} {dt.day}, {dt.year}"


def digest_title(meta: dict) -> str:
    """The digest's one-line title — the email subject AND the HTML header, so
    the two always agree.

    In-season it names the week ("2026 season, week 7"). In the offseason there
    is no week to name — "week 0" was both meaningless and misleading — so it
    names the date the digest was built instead ("2026 season, August 4, 2026").
    """
    season = meta.get("season")
    week = int(meta.get("weeks_completed") or 0)
    if week >= 1:
        return f"LOTG weekly digest — {season} season, week {week}"
    date = _meta_date(meta)
    return (f"LOTG weekly digest — {season} season, {date}" if date
            else f"LOTG weekly digest — {season} season")


def digest_sections(
    crossings: Sequence[Crossing] = (),
    projections: Sequence[Projection] = (),
    milestones: Sequence[Milestone] = (),
    records: Sequence[YearlyRecord] = (),
    highlights: Sequence[WeeklyHighlight] = (),
    events: Sequence["EventCrossing"] = (),
) -> List[Tuple[str, bool, list]]:
    """(title, grouped, items) for every non-empty digest section, in email order.

    The single place the digest's shape is declared. `render_digest_html` walks
    it to build the email and `email_summary` walks it to write the lede, so a
    new section appears in both by being added here and nowhere else — the lede
    can't silently stop covering a section the email grew.

    `grouped` is whether one entity's several items collapse under a single
    "<entity>:" label; a flat section prints one line each. Milestones are the
    only flat kind — a league total crossing a round number has no entity to
    group by.
    """
    def sect(sec):
        return [x for x in projections if x.section == sec]

    # In-season shows projections as "on pace"; a completed-season wrap resolves
    # them to final results ("finished Nth"), so the heading changes to match.
    yr_final = any(getattr(p, "final", False) for p in projections)
    yr_title = "Season-long results" if yr_final else "On pace this season"

    out: List[Tuple[str, bool, list]] = [
        ("Single-week records (this week)", True, list(highlights)),
        ("All-time leaderboard moves — players", True,
         [c for c in crossings if c.section == "players"]),
        ("All-time leaderboard moves — teams", True,
         [c for c in crossings if c.section == "teams"]),
        ("New single-season records", True, list(records)),
        ("League milestones", False, list(milestones)),
        (f"{yr_title} — players", True, sect("players")),
        (f"{yr_title} — teams", True, sect("teams")),
        (f"{yr_title} — league", True, sect("league")),
    ]
    # One section per board sheet, in _BOARD_SHEETS order.
    out += [(f"All-time leaderboard moves — {cfg['title']}", True,
             [e for e in events if e.sheet == sheet])
            for sheet, cfg in _BOARD_SHEETS.items()]
    return [(t, g, items) for t, g, items in out if items]


def render_digest_html(
    crossings: Sequence[Crossing],
    projections: Sequence[Projection],
    meta: dict,
    milestones: Sequence[Milestone] = (),
    records: Sequence[YearlyRecord] = (),
    highlights: Sequence[WeeklyHighlight] = (),
    header: Optional[str] = None,
    intro: str = "",
    events: Sequence["EventCrossing"] = (),
) -> str:
    if header is None:
        header = digest_title(meta)

    body = [
        '<div style="max-width:680px;margin:0 auto;padding:16px;">',
        f'  <h1 style="font:700 22px/1.3 system-ui,sans-serif;'
        f'color:#0b2545;margin:0 0 4px;">{header}</h1>',
        (f'  <p style="font:16px/1.5 system-ui,sans-serif;color:#0b2545;'
         f'margin:0 0 8px;padding:12px 14px;background:#f2f6fb;'
         f'border-left:3px solid #0b2545;border-radius:4px;">{intro}</p>'
         if intro else ""),
    ]
    for title, grouped, items in digest_sections(
            crossings, projections, milestones, records, highlights, events):
        body.append(_grouped_section_html(title, items) if grouped
                    else _section_html(title, [_line_of(i)
                                               for i in sorted(items, key=_order_key)]))
    if not any([highlights, crossings, records, milestones, projections, events]):
        body.append('  <p style="font:15px system-ui,sans-serif;color:#666;">'
                     'No leaderboard changes this week.</p>')
    body.append("</div>")
    return "\n".join(b for b in body if b)


def digest_is_empty(crossings, projections, milestones=(), records=(),
                    highlights=(), events=()) -> bool:
    return not any([crossings, projections, milestones, records, highlights, events])


def _champion_of(team_year: pd.DataFrame, season: int) -> Optional[str]:
    if team_year.empty or "Result" not in team_year.columns:
        return None
    yr = pd.to_numeric(team_year["Year"], errors="coerce")
    sub = team_year[(yr == season) & team_year["Result"].astype(str).str.contains("hampion", na=False)]
    return str(sub.iloc[0]["Team"]) if len(sub) else None


def build_replica_html(frames: dict, season: Optional[int] = None,
                       week: Optional[int] = None) -> str:
    """The offseason seed for the test email — deliberately MINIMAL.

    A real digest reports "changes to the top/bottom-5 of every stat since the
    previous email", which needs a previous email's snapshot. In the offseason
    there is none, and the derived all-time / year rollups can't be reconstructed
    for a single past week from the final exports. So rather than fake it, the
    offseason test email is a short confirmation (champion of the last season).
    During the season, the test button replays the last REAL weekly email instead,
    which is complete. Returns "" if no completed season is on record."""
    tw = frames.get("team_week", pd.DataFrame())
    if season is None or week is None:
        sw = latest_completed_season_week(tw)
        if sw is None:
            return ""
        season, week = sw
    champ = _champion_of(frames.get("team_year", pd.DataFrame()), season)
    intro = (f"🏆 {champ} won the {season} championship." if champ
             else f"The {season} season is complete.")
    note = ("This is the offseason, so there are no week-over-week changes to "
            "report yet. During the season, each Tuesday email lists every change "
            "to the top/bottom 5 of every stat since the previous week.")
    return (f'<div style="max-width:680px;margin:0 auto;padding:16px;'
            f'font:15px/1.5 system-ui,sans-serif;color:#333;">'
            f'<h1 style="font:700 22px/1.3 system-ui,sans-serif;color:#0b2545;'
            f'margin:0 0 8px;">LOTG digest — {season} season wrap</h1>'
            f'<p style="color:#0b2545;font-size:16px;margin:0 0 8px;">{intro}</p>'
            f'<p style="color:#666;margin:0;">{note}</p></div>')


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------
def load_snapshot(path: Path) -> Optional[dict]:
    try:
        return json.loads(Path(path).read_text())
    except (OSError, ValueError):
        return None


def save_snapshot(path: Path, snapshot: dict) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(snapshot, separators=(",", ":"), sort_keys=True))
