"""Phase 14 — in-season weekly digest: rank-snapshot + diff + projection engine.

This is the *data core* of the digest email — pure logic, no network / SMTP, so
it is fully unit-testable offline against the built CSVs. `scripts/build_digest.py`
wires it to `exports/`; `scripts/send_digest.py` mails the rendered HTML.

The digest is deliberately **over-inclusive**: instead of a hand-curated set of
"headline" stats, it auto-discovers *every* numeric column in the ranked sheets
and reports movement on all of them. Two kinds of item:

  1. **All-time crossings** (players + teams). For every numeric column in
     `player_all_time` / `team_all_time`, watch the top and bottom `WINDOW` of
     the leaderboard and report when an entity crosses another there
     (e.g. "Kyler Murray passes JJ McCarthy for 4th-lowest Points all-time").
     Detected by diffing this week's ranking snapshot against last week's.

  2. **Yearly on-pace projections** (players + teams + league). For every
     numeric column in `player_year` / `team_year` / `league_year`, project the
     in-progress season to a full-season pace (cumulative stats scale by weeks
     played; rate/level stats carry as-is) and report where the projection lands
     in the top/bottom `WINDOW` versus every completed season
     (e.g. "Oliverwkw is on pace for 4th-highest Hardship this season").
     **Yearly items are withheld until week 3** (too little signal earlier), per
     the phase spec.

`plan/phase14_phrasing.csv` (generated by `phrasing_catalog()`) documents the
exact sentence template for every discovered stat.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple
import json
import math

import pandas as pd


# ---------------------------------------------------------------------------
# Tunables
# ---------------------------------------------------------------------------
# Default top/bottom N of a leaderboard that counts as a notable "move".
WINDOW = 5

# Yearly ("on pace") items are withheld until this many weeks are complete.
MIN_YEARLY_WEEK = 3

# Per-section rules for ALL-TIME crossings (diff of this week's ranking vs last):
#   * players: huge board -> watch the top AND bottom 5, cap at half the board.
#   * teams: only 8 of them, so report ANY movement among the 8. High end only
#     (every rank change has a riser; reporting the riser once avoids the
#     double "riser Nth-highest + faller Mth-lowest" for a single swap), full
#     board (window=None), no half cap.
# league_all_time is a single row (no ranking) -> handled by milestones instead.
CROSSING_CONFIG = {
    "players": {"ends": ("high", "low"), "window": WINDOW, "cap_half": True},
    "teams":   {"ends": ("high",),       "window": None,   "cap_half": False},
}

# Per-section window for YEARLY on-pace projections. players/teams fixed at 5;
# league_year uses floor(#seasons / 3) capped at 5 (few seasons -> tiny window).
PROJECTION_WINDOW = {"players": WINDOW, "teams": WINDOW}
LEAGUE_WINDOW_CAP = 5

# league_all_time "major" cumulative totals that earn a milestone note when they
# cross a round number. (No leaderboard for a single-row sheet.)
MAJOR_LEAGUE_STATS = (
    "PF", "Number of transactions", "Total trades",
    "Number of donuts", "Amount of FAAB spent",
)

# Sentinels the build writes for "no value" — treated as missing for ranking.
_MISSING = {"N/A", "In Progress", "", "None", "nan", "NaN"}

# Columns that are identity / keys, never ranked even though some are numeric.
_KEY_COLS = {
    "Player", "Team", "Year", "Week", "Week Name", "Opponent",
    "Top team", "Top Team", "Last team", "Rookie?", "Result",
    "Taxi-eligible",
}

# A yearly stat is treated as a *rate/level* (projected as-is, not scaled by
# weeks played) when its name contains any of these markers; otherwise it is a
# *cumulative* count/total and scales linearly with weeks played. This split is
# surfaced in the phrasing CSV so it can be reviewed and corrected per column.
_RATE_MARKERS = (
    "%", "avg", "average", "ppg", "per game", "per season", "win %",
    "efficiency", "skill", "percentile", "volatility", "floor", "ceiling",
    "age", "variance", "differential", "boom", "bust", "quartile",
    "middle 50", "range", "diff", "streak", "remaining", "rate",
    "highest starter", "lowest starter", "playoff tiebreaker",
)


# ---------------------------------------------------------------------------
# Parsing helpers
# ---------------------------------------------------------------------------
def _to_float(value) -> Optional[float]:
    """Parse a cell to float, or None for sentinels / unparseable values."""
    if value is None:
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    s = str(value).strip()
    if s in _MISSING:
        return None
    s = s.replace(",", "").rstrip("%")
    try:
        return float(s)
    except ValueError:
        return None


def _ordinal(n: int) -> str:
    if 10 <= (n % 100) <= 20:
        suf = "th"
    else:
        suf = {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suf}"


def _fmt(value: float) -> str:
    """Compact number render: ints as grouped ints, else 1 decimal."""
    if abs(value - round(value)) < 1e-9:
        return f"{int(round(value)):,}"
    return f"{value:,.1f}"


def is_rate_stat(column: str) -> bool:
    """True if a yearly stat is a rate/level (projected as-is, not scaled)."""
    c = column.lower()
    return any(m in c for m in _RATE_MARKERS)


def is_weekly_counting_stat(column: str) -> bool:
    """True for stats that tally a per-week boolean outcome (max one per week) —
    the weekly awards (`Times ...`) and the result-flip counterfactuals
    (`Wins/Losses from hardship`, `Wins/Losses from byes`). These do NOT get an
    on-pace projection (you can't be "on pace for 8.5 awards"); movement on them
    is surfaced only through their all-time crossings (players top/bottom 5,
    teams any-of-8)."""
    c = column.lower()
    return c.startswith("times ") or "wins from" in c or "losses from" in c


# ---------------------------------------------------------------------------
# Column discovery
# ---------------------------------------------------------------------------
def discover_numeric_columns(df: pd.DataFrame, entity_col: str,
                             extra_skip: Sequence[str] = ()) -> List[str]:
    """Every column that ranks: not a key, and with >= 2 numeric values.

    Record strings ("34-20"), result labels ("Champion"), and team-name columns
    fail float parsing and are dropped automatically, so this stays truly
    over-inclusive without a hand-maintained exclusion list.
    """
    skip = set(_KEY_COLS) | {entity_col} | set(extra_skip)
    cols: List[str] = []
    for c in df.columns:
        if c in skip:
            continue
        numeric = sum(1 for v in df[c] if _to_float(v) is not None)
        if numeric >= 2:
            cols.append(c)
    return cols


# ---------------------------------------------------------------------------
# Rankings (descending: index 0 = highest value; tail = lowest)
# ---------------------------------------------------------------------------
def rank_column(df: pd.DataFrame, entity_col: str, column: str) -> List[dict]:
    """Ordered [{'entity','value'}] high -> low for one column (ties by name)."""
    if column not in df.columns or entity_col not in df.columns:
        return []
    rows = []
    for _, r in df.iterrows():
        v = _to_float(r[column])
        if v is None:
            continue
        rows.append({"entity": str(r[entity_col]), "value": v})
    rows.sort(key=lambda e: (-e["value"], e["entity"]))
    return rows


def _rankings_for(df: pd.DataFrame, entity_col: str,
                  columns: Sequence[str]) -> Dict[str, List[dict]]:
    out: Dict[str, List[dict]] = {}
    for col in columns:
        ranked = rank_column(df, entity_col, col)
        if len(ranked) >= 2:
            out[col] = ranked
    return out


# ---------------------------------------------------------------------------
# Season / week helpers
# ---------------------------------------------------------------------------
def current_season(team_year: pd.DataFrame) -> Optional[int]:
    if "Year" not in team_year.columns:
        return None
    yrs = pd.to_numeric(team_year["Year"], errors="coerce").dropna()
    return int(yrs.max()) if len(yrs) else None


def weeks_completed(team_week: pd.DataFrame, season: int) -> int:
    """Distinct completed weeks for `season` (the build only writes a week once
    it is final, per the Phase 5E freshness gate). 0 => offseason."""
    if team_week.empty or "Year" not in team_week.columns or "Week" not in team_week.columns:
        return 0
    sub = team_week[pd.to_numeric(team_week["Year"], errors="coerce") == season]
    weeks = pd.to_numeric(sub["Week"], errors="coerce").dropna().unique()
    return int(len(weeks))


# ---------------------------------------------------------------------------
# Snapshot (all-time rankings, for week-over-week diffing)
# ---------------------------------------------------------------------------
def build_snapshot(
    player_all_time: pd.DataFrame,
    team_all_time: pd.DataFrame,
    team_year: pd.DataFrame,
    team_week: pd.DataFrame,
    league_all_time: Optional[pd.DataFrame] = None,
    captured_at: Optional[datetime] = None,
) -> dict:
    captured_at = captured_at or datetime.now(timezone.utc)
    season = current_season(team_year)
    weeks = weeks_completed(team_week, season) if season is not None else 0
    p_cols = discover_numeric_columns(player_all_time, "Player")
    t_cols = discover_numeric_columns(team_all_time, "Team")
    return {
        "meta": {
            "captured_at": captured_at.isoformat(),
            "season": season,
            "weeks_completed": weeks,
        },
        "players": _rankings_for(player_all_time, "Player", p_cols),
        "teams": _rankings_for(team_all_time, "Team", t_cols),
        "league_milestones": league_milestone_values(
            league_all_time if league_all_time is not None else pd.DataFrame()),
    }


def is_in_season(snapshot: dict) -> bool:
    return int(snapshot.get("meta", {}).get("weeks_completed", 0) or 0) >= 1


# ---------------------------------------------------------------------------
# Crossings (diff)
# ---------------------------------------------------------------------------
@dataclass
class Crossing:
    section: str        # "players" | "teams"
    column: str
    end: str            # "high" | "low"
    rank: int           # position from the watched end (1-indexed)
    mover: str
    passed: str
    value: float

    def group(self) -> str:
        return self.mover

    def detail(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        return (f"passes {self.passed} for {_ordinal(self.rank)}-{end_word} "
                f"{self.column} ({_fmt(self.value)})")

    def sentence(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        return (f"{self.mover} passes {self.passed} for "
                f"{_ordinal(self.rank)}-{end_word} {self.column} all-time "
                f"({_fmt(self.value)}).")


def _rank_map(entries: Sequence[dict]) -> Dict[str, int]:
    return {e["entity"]: i + 1 for i, e in enumerate(entries)}


def _column_crossings(section: str, column: str,
                      prev: Sequence[dict], curr: Sequence[dict],
                      ends: Sequence[str], window: Optional[int],
                      cap_half: bool) -> List[Crossing]:
    """Crossings within the watched end(s) of one column.

    `window=None` watches the whole board (used for the 8-team league, "any
    movement in the 8"). When `cap_half` is set the window is capped at half the
    board so the top and bottom ends never overlap — otherwise a mid-table swap
    on a small board would be reported at BOTH ends (riser "Nth-highest" AND
    faller "Mth-lowest"). On the huge player board the cap never binds.
    """
    out: List[Crossing] = []
    prev_rank = _rank_map(prev)
    n = len(curr)
    window = n if window is None else window
    if cap_half:
        window = min(window, max(1, n // 2))
    for end in ends:
        slots = range(0, min(window, n)) if end == "high" \
            else range(max(0, n - window), n)
        for idx in slots:
            mover = curr[idx]["entity"]
            if mover not in prev_rank:
                continue
            new_rank = idx + 1
            old_rank = prev_rank[mover]
            improved = (new_rank < old_rank) if end == "high" else (new_rank > old_rank)
            if not improved:
                continue
            neighbor_idx = idx + 1 if end == "high" else idx - 1
            if not (0 <= neighbor_idx < n):
                continue
            passed = curr[neighbor_idx]["entity"]
            passed_old = prev_rank.get(passed)
            if passed_old is None:
                continue
            flipped = (passed_old < old_rank) if end == "high" else (passed_old > old_rank)
            if not flipped:
                continue
            display_rank = new_rank if end == "high" else (n - idx)
            out.append(Crossing(section, column, end, display_rank,
                                mover, passed, curr[idx]["value"]))
    return out


def diff_snapshots(prev: dict, curr: dict) -> List[Crossing]:
    """All all-time leaderboard crossings between two snapshots, per the
    per-section rules in CROSSING_CONFIG (players top/bottom 5; teams any-of-8)."""
    crossings: List[Crossing] = []
    for section, cfg in CROSSING_CONFIG.items():
        prev_sec = prev.get(section, {})
        curr_sec = curr.get(section, {})
        for column, curr_list in curr_sec.items():
            prev_list = prev_sec.get(column)
            if not prev_list:
                continue
            crossings.extend(_column_crossings(
                section, column, prev_list, curr_list,
                cfg["ends"], cfg["window"], cfg["cap_half"],
            ))
    return crossings


# ---------------------------------------------------------------------------
# On-pace projections
# ---------------------------------------------------------------------------
@dataclass
class Projection:
    section: str        # "players" | "teams" | "league"
    entity: str
    column: str
    end: str            # "high" | "low"
    rank: int
    total: int
    projected: float
    final: bool = False  # season complete -> "finished Nth" instead of "on pace"

    def group(self) -> str:
        return "The league" if self.section == "league" else self.entity

    def detail(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        return f"{_ordinal(self.rank)}-{end_word} {self.column} ({_fmt(self.projected)})"

    def sentence(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        val = _fmt(self.projected)
        if self.final:
            return (f"{self.group()} finished with the {_ordinal(self.rank)}-{end_word} "
                    f"{self.column} of any season ({val}).")
        return (f"{self.group()} is on pace for {_ordinal(self.rank)}-{end_word} "
                f"{self.column} this season ({val}).")


def _is_boolean(values: Sequence[float]) -> bool:
    """True if every value is 0 or 1 — a per-season flag that can't be projected
    'on pace' (e.g. #363's 'Rostered by champion?')."""
    return bool(values) and all(v in (0.0, 1.0) for v in values)


def _season_horizon(week_frame: pd.DataFrame, current: int) -> Optional[int]:
    """Full-season week count = max week seen in a completed prior season."""
    if week_frame.empty or "Year" not in week_frame.columns or "Week" not in week_frame.columns:
        return None
    years = pd.to_numeric(week_frame["Year"], errors="coerce")
    weeks = pd.to_numeric(week_frame["Week"], errors="coerce")
    prior_max = 0
    for y in sorted({int(v) for v in years.dropna().unique() if int(v) < current}):
        wk = weeks[years == y].dropna()
        if len(wk):
            prior_max = max(prior_max, int(wk.max()))
    return prior_max or None


def _project_frame(
    section: str,
    year_df: pd.DataFrame,
    entity_col: str,
    season: int,
    scale: float,
    window: int,
) -> List[Projection]:
    """Project every numeric yearly column for one sheet and keep the notable
    (top/bottom window) projections ranked against completed seasons."""
    cols = discover_numeric_columns(year_df, entity_col, extra_skip=("Year",))
    year_num = pd.to_numeric(year_df["Year"], errors="coerce")
    curr = year_df[year_num == season]
    hist = year_df[year_num < season]

    projections: List[Projection] = []
    for col in cols:
        if is_weekly_counting_stat(col):
            continue  # awards / result-flip tallies -> actual-value records path
        hist_vals = [v for v in (_to_float(x) for x in hist[col]) if v is not None]
        if len(hist_vals) < window:      # need a meaningful pool to rank against
            continue
        rate = is_rate_stat(col)
        # Project each current entity, then rank ALL entity-seasons (history +
        # this season's projections) together, by DISTINCT value, skipping any
        # value shared by more than _MAX_HIGHLIGHT_TIES (the only exclusion — this
        # is how 0/1 flags and heavily-tied stats fall out).
        proj_by_entity = []
        for _, r in curr.iterrows():
            cur = _to_float(r[col])
            if cur is None:
                continue
            entity = str(r[entity_col]) if entity_col in year_df.columns else str(season)
            proj_by_entity.append((entity, cur if rate else cur * scale))
        if not proj_by_entity:
            continue
        pool = hist_vals + [p for _, p in proj_by_entity]
        counts = _Counter(pool)
        high_rank = {v: i + 1 for i, v in enumerate(sorted(counts, reverse=True))}
        low_rank = {v: i + 1 for i, v in enumerate(sorted(counts))}
        total = len(pool)
        for entity, projected in proj_by_entity:
            if counts[projected] > _MAX_HIGHLIGHT_TIES:
                continue
            if high_rank[projected] <= window:
                projections.append(Projection(section, entity, col, "high",
                                              high_rank[projected], total, projected))
            elif low_rank[projected] <= window:
                projections.append(Projection(section, entity, col, "low",
                                              low_rank[projected], total, projected))
    return projections


def _league_window(league_year: pd.DataFrame) -> int:
    """league_year on-pace window = floor(#seasons / 3), capped at 5. With few
    seasons on record the league board is tiny, so the window shrinks with it."""
    if league_year.empty or "Year" not in league_year.columns:
        return 0
    n_seasons = pd.to_numeric(league_year["Year"], errors="coerce").dropna().nunique()
    return min(LEAGUE_WINDOW_CAP, n_seasons // 3)


def project_on_pace(
    player_year: pd.DataFrame,
    team_year: pd.DataFrame,
    league_year: pd.DataFrame,
    team_week: pd.DataFrame,
    min_week: int = MIN_YEARLY_WEEK,
) -> List[Projection]:
    """On-pace projections across player / team / league yearly sheets, per the
    per-section windows (players/teams top/bottom 5; league floor(#seasons/3)≤5).
    Weekly-counting stats (awards, result-flips) are excluded. Empty before
    `min_week` completed weeks, in the offseason, or before a completed prior
    season exists.
    """
    season = current_season(team_year)
    if season is None:
        return []
    played = weeks_completed(team_week, season)
    horizon = _season_horizon(team_week, season)
    if played < min_week or not horizon or played >= horizon:
        return []
    scale = horizon / played

    out: List[Projection] = []
    out += _project_frame("players", player_year, "Player", season, scale,
                          PROJECTION_WINDOW["players"])
    out += _project_frame("teams", team_year, "Team", season, scale,
                          PROJECTION_WINDOW["teams"])
    lw = _league_window(league_year)
    if lw >= 1 and not league_year.empty and "Year" in league_year.columns:
        out += _project_frame("league", league_year, "Year", season, scale, lw)
    return out


def pace_rank_map(projections: Sequence[Projection]) -> dict:
    """Compact {section: {stat: {entity: 'end:rank'}}} for snapshotting the
    on-pace standing, so next week can report only the ones that MOVED."""
    out: Dict[str, Dict[str, Dict[str, str]]] = {}
    for p in projections:
        out.setdefault(p.section, {}).setdefault(p.column, {})[p.entity] = f"{p.end}:{p.rank}"
    return out


def diff_pace(prior_pace: dict, projections: Sequence[Projection]) -> List[Projection]:
    """On-pace projections whose notable rank CHANGED since last week (or newly
    entered the top/bottom window). An entity that unchanged its standing is
    silent — this is what keeps the over-inclusive digest to a readable size."""
    changed: List[Projection] = []
    for p in projections:
        prior = prior_pace.get(p.section, {}).get(p.column, {}).get(p.entity)
        if prior != f"{p.end}:{p.rank}":
            changed.append(p)
    return changed


# ---------------------------------------------------------------------------
# Yearly records (for the weekly-counting stats that DON'T get on-pace)
# ---------------------------------------------------------------------------
# Weekly-counting stats (awards, result-flips) can't be projected "on pace", so
# instead we alert when the current season's ACTUAL value sets a new all-time
# single-season record — the most that stat has ever been in ANY season. Booleans
# are excluded (a 0/1 "record" is meaningless — those surface via all-time counts).
@dataclass
class YearlyRecord:
    section: str        # "players" | "teams" | "league"
    entity: str
    column: str
    value: float

    def group(self) -> str:
        return "The league" if self.section == "league" else self.entity

    def detail(self) -> str:
        return f"{self.column} ({_fmt(self.value)})"

    def sentence(self) -> str:
        return (f"{self.group()} sets a new single-season record for {self.column} "
                f"({_fmt(self.value)}) — most in any season.")


def _records_for_frame(section: str, year_df: pd.DataFrame,
                       entity_col: str, season: int) -> List[YearlyRecord]:
    if year_df.empty or "Year" not in year_df.columns:
        return []
    year_num = pd.to_numeric(year_df["Year"], errors="coerce")
    curr = year_df[year_num == season]
    hist = year_df[year_num < season]
    out: List[YearlyRecord] = []
    for col in discover_numeric_columns(year_df, entity_col, extra_skip=("Year",)):
        if not is_weekly_counting_stat(col):
            continue  # records here are only for the not-on-pace weekly stats
        hist_vals = [v for v in (_to_float(x) for x in hist[col]) if v is not None]
        if not hist_vals:
            continue  # need completed seasons to define a record to beat
        pairs = [(str(r[entity_col]) if entity_col in year_df.columns else str(season),
                  _to_float(r[col])) for _, r in curr.iterrows()]
        pairs = [(e, v) for e, v in pairs if v is not None]
        if not pairs:
            continue
        hist_max = max(hist_vals)
        curr_max = max(v for _, v in pairs)
        if curr_max <= hist_max:
            continue  # no new record this season
        holders = [e for e, v in pairs if abs(v - curr_max) < 1e-9]
        if len(holders) > _MAX_HIGHLIGHT_TIES:
            continue  # >5 tied for the "record" -> not notable (the >5-tied rule)
        for e in holders:
            out.append(YearlyRecord(section, e, col, curr_max))
    return out


def yearly_records(player_year: pd.DataFrame, team_year: pd.DataFrame,
                   league_year: pd.DataFrame, team_week: pd.DataFrame,
                   min_week: int = MIN_YEARLY_WEEK,
                   season: Optional[int] = None) -> List[YearlyRecord]:
    """New all-time single-season records set by weekly-counting stats. Defaults
    to the current season (withheld until `min_week` completed weeks); pass an
    explicit `season` (e.g. a finished season) to skip the week gate."""
    if season is None:
        season = current_season(team_year)
        if season is None or weeks_completed(team_week, season) < min_week:
            return []
    out: List[YearlyRecord] = []
    out += _records_for_frame("players", player_year, "Player", season)
    out += _records_for_frame("teams", team_year, "Team", season)
    if not league_year.empty and "Year" in league_year.columns:
        out += _records_for_frame("league", league_year, "Year", season)
    return out


def record_value_map(records: Sequence[YearlyRecord]) -> dict:
    """{section: {stat: record_value}} snapshot so next week only re-reports a
    record when it's been beaten/extended, not every week it stands."""
    out: Dict[str, Dict[str, float]] = {}
    for r in records:
        out.setdefault(r.section, {})[r.column] = r.value
    return out


def diff_records(prior_map: dict, records: Sequence[YearlyRecord]) -> List[YearlyRecord]:
    """Records that are newly set or have grown past last week's record value."""
    changed: List[YearlyRecord] = []
    for r in records:
        prev = prior_map.get(r.section, {}).get(r.column)
        if prev is None or r.value > prev + 1e-9:
            changed.append(r)
    return changed


# ---------------------------------------------------------------------------
# Weekly single-week highlights (the WEEKLY sheets: player/team/league_week)
# ---------------------------------------------------------------------------
# Rank the just-completed week's single-week values against EVERY week ever, and
# surface the ones landing in the top/bottom `WINDOW` — "best/worst single week
# of all time" alerts. This is how the weekly sheets get directly involved in the
# digest (they otherwise only feed the year/all-time rollups). Booleans (per-week
# award flags) are skipped — their tallies show via the year/all-time paths.
from collections import Counter as _Counter

# A single-week value shared by more than this many week-rows is too common to be
# a "record" (e.g. the pile of 0s on percentile / streak columns, or a routinely
# tied max), so it's skipped on BOTH ends. Genuine extremes are near-unique.
_MAX_HIGHLIGHT_TIES = 5


@dataclass
class WeeklyHighlight:
    section: str        # "players" | "teams" | "league"
    entity: str
    column: str
    end: str            # "high" | "low"
    rank: int           # among every DISTINCT single-week value on record
    value: float

    def group(self) -> str:
        return "The league" if self.section == "league" else self.entity

    def detail(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        return f"{self.column} ({_fmt(self.value)}) — {_ordinal(self.rank)}-{end_word} single week ever"

    def sentence(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        return (f"{self.group()}'s {self.column} this week ({_fmt(self.value)}) is the "
                f"{_ordinal(self.rank)}-{end_word} single week ever.")


def latest_completed_week(team_week: pd.DataFrame, season: int) -> Optional[int]:
    if team_week.empty or "Year" not in team_week.columns or "Week" not in team_week.columns:
        return None
    sub = team_week[pd.to_numeric(team_week["Year"], errors="coerce") == season]
    weeks = pd.to_numeric(sub["Week"], errors="coerce").dropna()
    return int(weeks.max()) if len(weeks) else None


def latest_completed_season_week(team_week: pd.DataFrame) -> Optional[tuple]:
    """The most recent completed (season, week) across ALL seasons — i.e. the
    last week that has games on record (the championship week of the latest
    finished season in the offseason). Drives the 'most recent digest' replica."""
    if team_week.empty or "Year" not in team_week.columns:
        return None
    years = pd.to_numeric(team_week["Year"], errors="coerce").dropna()
    if not len(years):
        return None
    season = int(years.max())
    week = latest_completed_week(team_week, season)
    return (season, week) if week else None


def _highlights_for_frame(section: str, wk_df: pd.DataFrame, entity_col: str,
                          season: int, week: int, window: int,
                          skip: Sequence[str] = ()) -> List[WeeklyHighlight]:
    if wk_df.empty or "Year" not in wk_df.columns or "Week" not in wk_df.columns:
        return []
    year = pd.to_numeric(wk_df["Year"], errors="coerce")
    wknum = pd.to_numeric(wk_df["Week"], errors="coerce")
    this_week = wk_df[(year == season) & (wknum == week)]
    if this_week.empty:
        return []
    has_entity = entity_col in wk_df.columns

    out: List[WeeklyHighlight] = []
    for col in discover_numeric_columns(wk_df, entity_col):
        if col in skip:
            continue  # two-sided (margin, PF gap) — handled by matchup_highlights
        all_vals = [v for v in (_to_float(x) for x in wk_df[col]) if v is not None]
        if len(all_vals) < window:
            continue
        # Both ends (some stats go negative, so "lowest ever" is meaningful).
        # Rank by DISTINCT value so ties share a rank; the ONLY exclusion is a
        # value shared by more than _MAX_HIGHLIGHT_TIES rows (that's how booleans
        # and heavily-tied cumulative extremes fall out — per the >5-tied rule).
        counts = _Counter(all_vals)
        high_rank = {v: i + 1 for i, v in enumerate(sorted(counts, reverse=True))}
        low_rank = {v: i + 1 for i, v in enumerate(sorted(counts))}
        for _, r in this_week.iterrows():
            v = _to_float(r[col])
            if v is None or counts[v] > _MAX_HIGHLIGHT_TIES:
                continue
            entity = str(r[entity_col]) if has_entity else "The league"
            if high_rank[v] <= window:
                out.append(WeeklyHighlight(section, entity, col, "high", high_rank[v], v))
            elif low_rank[v] <= window:
                out.append(WeeklyHighlight(section, entity, col, "low", low_rank[v], v))
    return out


def weekly_highlights(player_week: pd.DataFrame, team_week: pd.DataFrame,
                      league_week: pd.DataFrame, team_year: pd.DataFrame,
                      window: int = WINDOW,
                      season: Optional[int] = None,
                      week: Optional[int] = None) -> List[WeeklyHighlight]:
    """Top/bottom-`window` single-week performances in a completed week, ranked
    against every week on record. Defaults to the current season's latest week
    (empty in the offseason); pass explicit season/week for a past week."""
    if season is None:
        season = current_season(team_year)
    if season is None:
        return []
    if week is None:
        week = latest_completed_week(team_week, season)
    if not week:
        return []
    team_skip = two_sided_columns(team_week, "Team", "Opponent", ["Year", "Week"]) \
        if not team_week.empty and "Opponent" in team_week.columns else []
    out: List[WeeklyHighlight] = []
    out += _highlights_for_frame("players", player_week, "Player", season, week, window)
    out += _highlights_for_frame("teams", team_week, "Team", season, week, window, skip=team_skip)
    out += _highlights_for_frame("league", league_week, "Year", season, week, window)
    return out


# ---------------------------------------------------------------------------
# Event highlights (picks / trades / transactions — event-log sheets)
# ---------------------------------------------------------------------------
# These sheets are per-event, not per-entity leaderboards. So we rank each
# event's value against EVERY event of that kind ever, and surface the top/bottom
# extremes among a target set of events (a season's, for the wrap; a week's, for
# the live digest). "The best pick of 2025 (O-Score) — 2nd-highest ever."
@dataclass
class EventHighlight:
    sheet: str          # "picks" | "trades" | "transactions"
    label: str          # human name of the event (e.g. "2025 pick 1.01 (…)")
    column: str
    end: str            # "high" | "low"
    rank: int
    value: float

    def group(self) -> str:
        return self.label

    def detail(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        return (f"{self.column} of {_fmt(self.value)} — "
                f"{_ordinal(self.rank)}-{end_word} of any {self.sheet[:-1]} ever")

    def sentence(self) -> str:
        end_word = "highest" if self.end == "high" else "lowest"
        return (f"{self.label}: {self.column} of {_fmt(self.value)} — "
                f"{_ordinal(self.rank)}-{end_word} of any {self.sheet[:-1]} ever.")


def _event_label(sheet: str, row) -> str:
    def g(c):
        v = row.get(c) if hasattr(row, "get") else None
        return "" if v is None or (isinstance(v, float) and math.isnan(v)) else str(v)
    if sheet == "picks":
        return f"{g('Year')} pick {g('Number')} ({g('Player Picked')})".strip()
    if sheet == "trades":
        return f"{g('Team')}'s {g('Date')} trade".strip()
    if sheet == "transactions":
        who = g("Player Added") or g("Player Dropped")
        return f"{g('Team')}'s move for {who}".strip()
    return sheet


def event_highlights(df: pd.DataFrame, sheet: str, season_col: str,
                     target_season: int, window: int = WINDOW,
                     max_ties: int = _MAX_HIGHLIGHT_TIES,
                     skip: Sequence[str] = ()) -> List[EventHighlight]:
    """Top/bottom-`window` events (by each numeric column) among `target_season`'s
    events, ranked against every event of that kind ever. Values shared by more
    than `max_ties` events are skipped (common values aren't records). Columns in
    `skip` (two-sided differentials) are handled by paired_highlights instead."""
    if df is None or df.empty or season_col not in df.columns:
        return []
    season_num = pd.to_numeric(df[season_col], errors="coerce")
    target = df[season_num == target_season]
    if target.empty:
        return []
    out: List[EventHighlight] = []
    for col in discover_numeric_columns(df, season_col):
        if col in skip:
            continue
        all_vals = [v for v in (_to_float(x) for x in df[col]) if v is not None]
        if len(all_vals) < window:
            continue
        counts = _Counter(all_vals)
        high_rank = {v: i + 1 for i, v in enumerate(sorted(counts, reverse=True))}
        low_rank = {v: i + 1 for i, v in enumerate(sorted(counts))}
        for _, r in target.iterrows():
            v = _to_float(r[col])
            if v is None or counts[v] > max_ties:
                continue
            if high_rank[v] <= window:
                out.append(EventHighlight(sheet, _event_label(sheet, r), col, "high", high_rank[v], v))
            elif low_rank[v] <= window:
                out.append(EventHighlight(sheet, _event_label(sheet, r), col, "low", low_rank[v], v))
    return out


_TRADE_OPP = "Team's traded with 1"
_TRADE_IDS = ("Date", "Season")


def season_event_highlights(frames: dict, season: int,
                            window: int = WINDOW) -> List[EventHighlight]:
    """Event highlights across picks / trades / transactions for one season.
    Two-sided trade differentials (KTC/age) are excluded here — they're paired
    up separately by `season_paired_highlights`."""
    trades = frames.get("trades", pd.DataFrame())
    trade_skip = two_sided_columns(trades, "Team", _TRADE_OPP, _TRADE_IDS)
    out: List[EventHighlight] = []
    out += event_highlights(frames.get("picks", pd.DataFrame()), "picks", "Year", season, window)
    out += event_highlights(trades, "trades", "Season", season, window, skip=trade_skip)
    out += event_highlights(frames.get("transactions", pd.DataFrame()), "transactions", "Season", season, window)
    return out


def matchup_highlights(team_week: pd.DataFrame, season: int, week: int,
                       window: int = WINDOW) -> List[PairedHighlight]:
    """Two-sided matchup extremes for one completed week (margin, pregame-max-PF
    gap): each game ranked by |value| against every game ever, both teams named."""
    if team_week is None or team_week.empty or "Opponent" not in team_week.columns:
        return []
    cols = two_sided_columns(team_week, "Team", "Opponent", ["Year", "Week"])
    if not cols:
        return []
    year = pd.to_numeric(team_week["Year"], errors="coerce")
    wknum = pd.to_numeric(team_week["Week"], errors="coerce")
    mask = (year == season) & (wknum == week)
    return paired_highlights(team_week, "Team", "Opponent", ["Year", "Week"],
                             "matchup", mask, cols, window=window)


def season_paired_highlights(frames: dict, season: int,
                             window: int = WINDOW) -> List[PairedHighlight]:
    """Two-sided trade extremes for one season (KTC / age differentials), each
    trade ranked by |value| against every trade ever, both teams named."""
    trades = frames.get("trades", pd.DataFrame())
    cols = two_sided_columns(trades, "Team", _TRADE_OPP, _TRADE_IDS)
    if not cols or trades.empty or "Season" not in trades.columns:
        return []
    mask = pd.to_numeric(trades["Season"], errors="coerce") == season
    return paired_highlights(trades, "Team", _TRADE_OPP, list(_TRADE_IDS),
                             "trade", mask, cols, window=window)


# ---------------------------------------------------------------------------
# Zero-centered / two-sided stats (margins, KTC & age differentials)
# ---------------------------------------------------------------------------
# A two-sided stat is the SAME event seen from both sides: a matchup's margin is
# +M for the winner and -M for the loser; a trade's net KTC is +X / -X. Ranking
# the raw value would report the two mirror rows as separate "records", so instead
# we rank by ABSOLUTE value (biggest blowout / closest game; most lopsided /
# most even trade) and name BOTH sides in one row.
@dataclass
class PairedHighlight:
    scope: str          # "matchup" | "trade" | "transaction"
    a: str
    b: str
    column: str
    end: str            # "high" = largest |value|, "low" = smallest |value|
    rank: int
    magnitude: float

    def group(self) -> str:
        return f"The {self.scope} between {self.a} and {self.b}"

    def detail(self) -> str:
        end_word = "largest" if self.end == "high" else "smallest"
        return f"{_ordinal(self.rank)}-{end_word} {self.column} ever ({_fmt(self.magnitude)})"

    def sentence(self) -> str:
        end_word = "largest" if self.end == "high" else "smallest"
        return (f"The {self.scope} between {self.a} and {self.b} had the "
                f"{_ordinal(self.rank)}-{end_word} {self.column} of all time "
                f"({_fmt(self.magnitude)}).")


def two_sided_columns(df: pd.DataFrame, entity_col: str, opp_col: str,
                      id_cols: Sequence[str]) -> List[str]:
    """Numeric columns that are genuinely two-sided: for most events the pair's
    two rows hold mirror values (a ≈ -b). Detected from the data, no name list."""
    if df is None or df.empty or opp_col not in df.columns:
        return []
    out: List[str] = []
    for col in discover_numeric_columns(df, entity_col):
        groups: Dict[tuple, list] = {}
        for _, r in df.iterrows():
            v = _to_float(r[col])
            if v is None:
                continue
            a, b = str(r[entity_col]), str(r.get(opp_col) or "")
            if not b:
                continue
            key = tuple(str(r.get(c, "")) for c in id_cols) + tuple(sorted([a, b]))
            groups.setdefault(key, []).append(v)
        mirror = tot = 0
        for vs in groups.values():
            if len(vs) != 2:
                continue
            mag = max(abs(vs[0]), abs(vs[1]))
            if mag <= 1e-6:
                continue  # a 0/0 pair is trivially "mirrored"; not a real two-sided stat
            tot += 1
            if abs(vs[0] + vs[1]) <= 1e-6 + 0.01 * mag:
                mirror += 1
        if tot >= 3 and mirror / tot >= 0.8:
            out.append(col)
    return out


def paired_highlights(df: pd.DataFrame, entity_col: str, opp_col: str,
                      id_cols: Sequence[str], scope: str, target_mask,
                      cols: Sequence[str], window: int = WINDOW,
                      max_ties: int = _MAX_HIGHLIGHT_TIES) -> List[PairedHighlight]:
    """For each two-sided `col`, rank events by |value| (deduping the two mirror
    rows into one pair) and surface the top/bottom `window` among the target
    events (this week's matchups / this season's trades)."""
    if df is None or df.empty or opp_col not in df.columns:
        return []
    tgt = target_mask.reindex(df.index, fill_value=False) if hasattr(target_mask, "reindex") else target_mask
    out: List[PairedHighlight] = []
    for col in cols:
        seen = set()
        rows = []  # (a, b, |value|, in_target)
        for i, r in df.iterrows():
            v = _to_float(r[col])
            if v is None:
                continue
            a, b = str(r[entity_col]), str(r.get(opp_col) or "")
            if not b:
                continue
            key = tuple(str(r.get(c, "")) for c in id_cols) + tuple(sorted([a, b]))
            if key in seen:
                continue
            seen.add(key)
            rows.append((a, b, abs(v), bool(tgt.loc[i]) if hasattr(tgt, "loc") else bool(tgt[i])))
        if len(rows) < window:
            continue
        counts = _Counter(av for _, _, av, _ in rows)
        high_rank = {v: i + 1 for i, v in enumerate(sorted(counts, reverse=True))}
        low_rank = {v: i + 1 for i, v in enumerate(sorted(counts))}
        for a, b, av, in_tgt in rows:
            if not in_tgt or counts[av] > max_ties:
                continue
            if high_rank[av] <= window:
                out.append(PairedHighlight(scope, a, b, col, "high", high_rank[av], av))
            elif low_rank[av] <= window:
                out.append(PairedHighlight(scope, a, b, col, "low", low_rank[av], av))
    return out


def _paired_key(p: PairedHighlight) -> str:
    ab = "|".join(sorted([p.a, p.b]))
    return f"{p.scope}|{ab}|{p.column}|{p.end}:{p.rank}"


def paired_key_map(pairs: Sequence[PairedHighlight]) -> list:
    return sorted(_paired_key(p) for p in pairs)


def diff_paired(prior_keys, pairs: Sequence[PairedHighlight]) -> List[PairedHighlight]:
    prior = set(prior_keys or [])
    return [p for p in pairs if _paired_key(p) not in prior]


def _event_key(e: EventHighlight) -> str:
    return f"{e.sheet}|{e.label}|{e.column}|{e.end}:{e.rank}"


def event_key_map(events: Sequence[EventHighlight]) -> list:
    """Sorted event-highlight keys for the snapshot, so the live digest only
    re-reports a notable pick/trade/transaction when it's newly notable."""
    return sorted(_event_key(e) for e in events)


def diff_events(prior_keys, events: Sequence[EventHighlight]) -> List[EventHighlight]:
    prior = set(prior_keys or [])
    return [e for e in events if _event_key(e) not in prior]


# ---------------------------------------------------------------------------
# League all-time milestones (single-row sheet -> no leaderboard)
# ---------------------------------------------------------------------------
@dataclass
class Milestone:
    stat: str
    value: float
    milestone: float

    def sentence(self) -> str:
        return (f"League {self.stat} passes {_fmt(self.milestone)} "
                f"(now {_fmt(self.value)}).")


def league_milestone_values(league_all_time: pd.DataFrame) -> Dict[str, float]:
    """Current value of each major league_all_time total (single-row sheet)."""
    out: Dict[str, float] = {}
    if league_all_time is None or league_all_time.empty:
        return out
    row = league_all_time.iloc[0]
    for stat in MAJOR_LEAGUE_STATS:
        if stat in league_all_time.columns:
            v = _to_float(row[stat])
            if v is not None:
                out[stat] = v
    return out


def _round_step(v: float) -> Optional[float]:
    """Round-number granularity for milestones: the value's order of magnitude
    (e.g. 49,000 -> 10,000, so milestones fall on 40k / 50k / 60k)."""
    if v <= 0:
        return None
    return float(10 ** int(math.floor(math.log10(v))))


def milestone_crossings(prev_vals: Dict[str, float],
                        curr_vals: Dict[str, float]) -> List[Milestone]:
    """Major league totals that crossed a round number since last week."""
    out: List[Milestone] = []
    for stat, cur in curr_vals.items():
        prev = prev_vals.get(stat)
        if prev is None or cur is None or cur <= prev:
            continue
        step = _round_step(cur)
        if not step:
            continue
        crossed = math.floor(cur / step) * step   # largest round number <= cur
        if crossed > prev and crossed > 0:
            out.append(Milestone(stat, cur, crossed))
    return out


# ---------------------------------------------------------------------------
# Phrasing catalog (the reviewable "how every stat is phrased" CSV)
# ---------------------------------------------------------------------------
def phrasing_catalog(
    player_all_time: pd.DataFrame,
    team_all_time: pd.DataFrame,
    player_year: pd.DataFrame,
    team_year: pd.DataFrame,
    league_year: pd.DataFrame,
    league_all_time: Optional[pd.DataFrame] = None,
    player_week: Optional[pd.DataFrame] = None,
    team_week: Optional[pd.DataFrame] = None,
    league_week: Optional[pd.DataFrame] = None,
    picks: Optional[pd.DataFrame] = None,
    trades: Optional[pd.DataFrame] = None,
    transactions: Optional[pd.DataFrame] = None,
) -> List[dict]:
    """One row per (sheet, stat) describing exactly how a change is phrased."""
    rows: List[dict] = []

    def _add(sheet, stat, scope, scale, rise, fall):
        rows.append({"sheet": sheet, "stat": stat, "scope": scope, "scale": scale,
                     "phrase_when_rises": rise, "phrase_when_falls": fall})

    def _paired_add(sheet, col, scope_noun):
        # Two-sided (zero-centered) stat: ranked by |value|, both sides in one row.
        _add(sheet, col, "two-sided extreme (top/bottom 5 by |value|, both sides named)", "n/a",
             f"The {scope_noun} between <A> and <B> had the <N>th-largest {col} of all time (<value>).",
             f"The {scope_noun} between <A> and <B> had the <N>th-smallest {col} of all time (<value>).")

    def _event_rows(sheet, df, season_col, opp_col=None, id_cols=(), scope_noun=""):
        if df is None or df.empty:
            return
        singular = sheet[:-1]
        two_sided = set(two_sided_columns(df, "Team", opp_col, id_cols)) if opp_col else set()
        for col in discover_numeric_columns(df, season_col):
            if col in two_sided:
                _paired_add(sheet, col, scope_noun)
                continue
            _add(sheet, col, "event highlight (top/bottom 5 of all such events ever)", "n/a",
                 f"<event>: {col} of <value> — <N>th-highest of any {singular} ever.",
                 f"<event>: {col} of <value> — <N>th-lowest of any {singular} ever.")

    def _weekly_rows(sheet, df, entity_col, who, opp_col=None, id_cols=(), scope_noun=""):
        if df is None or df.empty:
            return
        two_sided = set(two_sided_columns(df, entity_col, opp_col, id_cols)) if opp_col else set()
        for col in discover_numeric_columns(df, entity_col):
            if col in two_sided:
                _paired_add(sheet, col, scope_noun)
                continue
            _add(sheet, col, "single-week record (top/bottom 5 of all weeks ever)", "n/a",
                 f"{who}'s {col} this week (<value>) is the <N>th-highest single week ever.",
                 f"{who}'s {col} this week (<value>) is the <N>th-lowest single week ever.")

    def _crossing_rows(sheet, df, entity_col, who, scope):
        for col in discover_numeric_columns(df, entity_col):
            _add(sheet, col, scope, "n/a",
                 f"{who} passes <other> for <N>th-highest {col} all-time (<value>).",
                 f"{who} passes <other> for <N>th-lowest {col} all-time (<value>).")

    def _pace_rows(sheet, df, entity_col, who, window_note):
        for col in discover_numeric_columns(df, entity_col, extra_skip=("Year",)):
            if is_weekly_counting_stat(col):
                # Weekly-counting (awards, result-flips) can't be projected, so
                # they alert when the season's actual value sets a new all-time
                # single-season record instead.
                _add(sheet, col, "yearly record (new single-season high, any year)", "n/a",
                     f"{who} sets a new single-season record for {col} (<value>) — most in any season.",
                     "")
                continue
            scale = "as-is (rate/level)" if is_rate_stat(col) else "scaled by weeks played"
            _add(sheet, col, f"yearly on-pace (from week {MIN_YEARLY_WEEK}; {window_note})", scale,
                 f"{who} is on pace for <N>th-highest {col} this season (<value>).",
                 f"{who} is on pace for <N>th-lowest {col} this season (<value>).")

    # player_all_time: top/bottom 5. team_all_time: any movement among the 8.
    _crossing_rows("player_all_time", player_all_time, "Player", "<player>",
                   "all-time change (top/bottom 5)")
    _crossing_rows("team_all_time", team_all_time, "Team", "<team>",
                   "all-time change (any movement among the 8)")

    _pace_rows("player_year", player_year, "Player", "<player>", "top/bottom 5")
    _pace_rows("team_year", team_year, "Team", "<team>", "top/bottom 5")
    _pace_rows("league_year", league_year, "Year", "The league",
               "top/bottom floor(#seasons/3), capped at 5")

    # Weekly sheets: single-week records ranked across every week ever. team_week
    # carries two-sided matchup stats (margin, PF gap) — those phrase as pairs.
    _weekly_rows("player_week", player_week, "Player", "<player>")
    _weekly_rows("team_week", team_week, "Team", "<team>",
                 opp_col="Opponent", id_cols=("Year", "Week"), scope_noun="matchup")
    _weekly_rows("league_week", league_week, "Year", "The league")

    # Event-log sheets: picks / trades / transactions ranked across all events.
    # trades carry two-sided differentials (KTC / age) — those phrase as pairs.
    _event_rows("picks", picks, "Year")
    _event_rows("trades", trades, "Season",
                opp_col=_TRADE_OPP, id_cols=_TRADE_IDS, scope_noun="trade")
    _event_rows("transactions", transactions, "Season")

    # league_all_time: milestones only (single-row sheet, no leaderboard).
    if league_all_time is not None and not league_all_time.empty:
        for col in MAJOR_LEAGUE_STATS:
            if col in league_all_time.columns:
                _add("league_all_time", col, "milestone (round-number crossing)", "n/a",
                     f"League {col} passes <round number> (now <value>).", "")
    return rows


def write_phrasing_csv(path: Path, rows: Sequence[dict]) -> None:
    df = pd.DataFrame(rows, columns=[
        "sheet", "stat", "scope", "scale", "phrase_when_rises", "phrase_when_falls",
    ])
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


# ---------------------------------------------------------------------------
# HTML render
# ---------------------------------------------------------------------------
def _section_html(title: str, lines: Sequence[str]) -> str:
    if not lines:
        return ""
    items = "\n".join(f"      <li>{ln}</li>" for ln in lines)
    return (
        f'  <h2 style="font:600 18px/1.3 system-ui,sans-serif;'
        f'margin:24px 0 8px;color:#1a2b3c;">{title}</h2>\n'
        f'    <ul style="margin:0;padding-left:20px;'
        f'font:15px/1.5 system-ui,sans-serif;color:#333;">\n{items}\n    </ul>\n'
    )


def _grouped_section_html(title: str, items: Sequence, verb: str) -> str:
    """Group items by their .group() so one entity's many items read as
    "<entity> <verb>:" + an indented sub-list, instead of an endless flat list.
    A group with a single item stays inline (its full .sentence())."""
    if not items:
        return ""
    groups: "Dict[str, list]" = {}
    for it in items:
        groups.setdefault(it.group(), []).append(it)
    lines = []
    for g, its in groups.items():
        if len(its) == 1:
            lines.append(its[0].sentence())
        else:
            sub = "".join(
                f'<li style="margin:0;">{i.detail()}</li>' for i in its)
            lines.append(
                f'{g} {verb}:'
                f'<ul style="margin:2px 0 6px;padding-left:20px;color:#555;">{sub}</ul>')
    return _section_html(title, lines)


def _proj_lines(projections: Sequence[Projection], section: str) -> List[str]:
    return [p.sentence() for p in projections if p.section == section]


def render_digest_html(
    crossings: Sequence[Crossing],
    projections: Sequence[Projection],
    meta: dict,
    milestones: Sequence[Milestone] = (),
    records: Sequence[YearlyRecord] = (),
    highlights: Sequence[WeeklyHighlight] = (),
    header: Optional[str] = None,
    intro: str = "",
    events: Sequence[EventHighlight] = (),
    paired: Sequence["PairedHighlight"] = (),
) -> str:
    def sect(sec):
        return [x for x in projections if x.section == sec]

    season = meta.get("season")
    week = meta.get("weeks_completed")
    if header is None:
        header = f"LOTG weekly digest — {season} season, through week {week}"

    # In-season shows projections as "on pace"; a completed-season wrap resolves
    # them to final results ("finished Nth"), so the heading changes to match.
    yr_final = any(getattr(p, "final", False) for p in projections)
    yr_title = "Season-long results" if yr_final else "On pace this season"
    pace_verb = "finished with the" if yr_final else "on pace for"

    body = [
        '<div style="max-width:680px;margin:0 auto;padding:16px;">',
        f'  <h1 style="font:700 22px/1.3 system-ui,sans-serif;'
        f'color:#0b2545;margin:0 0 4px;">{header}</h1>',
        (f'  <p style="font:16px/1.4 system-ui,sans-serif;color:#0b2545;'
         f'margin:0 0 8px;">{intro}</p>' if intro else ""),
        _grouped_section_html("Single-week records (this week)", list(highlights),
                              "had these single-week records"),
        _grouped_section_html("Matchup extremes",
                              [p for p in paired if p.scope == "matchup"], "was notable"),
        _grouped_section_html("All-time leaderboard moves — players",
                              [c for c in crossings if c.section == "players"], "made these all-time moves"),
        _grouped_section_html("All-time leaderboard moves — teams",
                              [c for c in crossings if c.section == "teams"], "made these all-time moves"),
        _grouped_section_html("New single-season records", list(records),
                              "set these single-season records"),
        _section_html("League milestones", [m.sentence() for m in milestones]),
        _grouped_section_html(f"{yr_title} — players", sect("players"), pace_verb),
        _grouped_section_html(f"{yr_title} — teams", sect("teams"), pace_verb),
        _grouped_section_html(f"{yr_title} — league", sect("league"), pace_verb),
        _grouped_section_html("Notable draft picks",
                              [e for e in events if e.sheet == "picks"], "was notable"),
        _grouped_section_html("Notable trades",
                              [e for e in events if e.sheet == "trades"], "was notable"),
        _grouped_section_html("Two-sided trade extremes",
                              [p for p in paired if p.scope == "trade"], "was notable"),
        _grouped_section_html("Notable transactions",
                              [e for e in events if e.sheet == "transactions"], "was notable"),
    ]
    if not any([highlights, crossings, records, milestones, projections, events, paired]):
        body.append('  <p style="font:15px system-ui,sans-serif;color:#666;">'
                     'No leaderboard changes this week.</p>')
    body.append("</div>")
    return "\n".join(b for b in body if b)


def digest_is_empty(crossings, projections, milestones=(), records=(),
                    highlights=(), events=(), paired=()) -> bool:
    return not any([crossings, projections, milestones, records, highlights, events, paired])


def _champion_of(team_year: pd.DataFrame, season: int) -> Optional[str]:
    if team_year.empty or "Result" not in team_year.columns:
        return None
    yr = pd.to_numeric(team_year["Year"], errors="coerce")
    sub = team_year[(yr == season) & team_year["Result"].astype(str).str.contains("hampion", na=False)]
    return str(sub.iloc[0]["Team"]) if len(sub) else None


def build_replica_html(frames: dict, season: Optional[int] = None,
                       week: Optional[int] = None) -> str:
    """The offseason seed for the test email — deliberately MINIMAL.

    A real digest reports "changes to the top/bottom-5 of every stat since the
    previous email", which needs a previous email's snapshot. In the offseason
    there is none, and the derived all-time / year rollups can't be reconstructed
    for a single past week from the final exports. So rather than fake it, the
    offseason test email is a short confirmation (champion of the last season).
    During the season, the test button replays the last REAL weekly email instead,
    which is complete. Returns "" if no completed season is on record."""
    tw = frames.get("team_week", pd.DataFrame())
    if season is None or week is None:
        sw = latest_completed_season_week(tw)
        if sw is None:
            return ""
        season, week = sw
    champ = _champion_of(frames.get("team_year", pd.DataFrame()), season)
    intro = (f"🏆 {champ} won the {season} championship." if champ
             else f"The {season} season is complete.")
    note = ("This is the offseason, so there are no week-over-week changes to "
            "report yet. During the season, each Tuesday email lists every change "
            "to the top/bottom 5 of every stat since the previous week.")
    return (f'<div style="max-width:680px;margin:0 auto;padding:16px;'
            f'font:15px/1.5 system-ui,sans-serif;color:#333;">'
            f'<h1 style="font:700 22px/1.3 system-ui,sans-serif;color:#0b2545;'
            f'margin:0 0 8px;">LOTG digest — {season} season wrap</h1>'
            f'<p style="color:#0b2545;font-size:16px;margin:0 0 8px;">{intro}</p>'
            f'<p style="color:#666;margin:0;">{note}</p></div>')


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------
def load_snapshot(path: Path) -> Optional[dict]:
    try:
        return json.loads(Path(path).read_text())
    except (OSError, ValueError):
        return None


def save_snapshot(path: Path, snapshot: dict) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(snapshot, separators=(",", ":"), sort_keys=True))
